### PR TITLE
helm-imenu supports showing item types by icons

### PR DESCRIPTION
**Pull request by taquangtrung**
Hi,

I created this PR to support showing icons in imenu types, like in the screenshot below:

helm-imenu

The icon files are borrowed from the `company` package. Users can always switch back to the default textual item type by setting `helm-imenu-show-icons` to `nil`.

Can you take a look at this PR and advise if it can be merged back?

Thank you!

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> Hi,
>
> I created this PR to support showing icons in imenu types, like in the screenshot below:
>
> helm-ime
>
> The icon files are borrowed from the company package. Users can always switch back to the default textual item type by setting helm-imenu-show-icons to nil.
>
> Can you take a look at this PR and advise if it can be merged back?

We do not want to require company just for this, a way to do this is to
use all-the-icons package, see how it is done in helm-find-files and
helm-bookmarks.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here a dirty patch just to show what we could do with all-the-icons:

```diff
diff --git a/helm-imenu.el b/helm-imenu.el
index 0844d6e2..9f1bb797 100644
--- a/helm-imenu.el
+++ b/helm-imenu.el
@@ -294,8 +294,18 @@ string."
         (and prop (push prop lst)))
       lst)))
 
+(defun helm-imenu-icon-for-type (type)
+  (require 'all-the-icons)
+  (helm-acase type
+    ("Variable"  (all-the-icons-octicon "book" :face font-lock-variable-name-face))
+    ("Variables" (all-the-icons-octicon "book":face font-lock-variable-name-face))
+    ("Function"  (all-the-icons-faicon "language" :face font-lock-function-name-face))
+    ("Types"     (all-the-icons-fileicon "typedoc" :face font-lock-type-face))
+    (t           (all-the-icons-alltheicon "atom"))))
+
 (defun helm-imenu-transformer (candidates)
-  (cl-loop for (k . v) in candidates
+  (cl-loop with type
+           for (k . v) in candidates
            ;; (k . v) == (symbol-name . marker)
            for bufname = (buffer-name
                           (pcase v
@@ -313,10 +323,14 @@ string."
                           (propertize
                            x 'face
                            (cl-loop for (p . f) in helm-imenu-type-faces
-                                    when (string-match p x) return f
+                                    when (string-match p x)
+                                    do (setq type (match-string 0 x))
+                                    and return f
                                     finally return 'default)))
                         types helm-imenu-delimiter)
-           for disp = (propertize disp1 'help-echo bufname 'types types)
+           for disp = (concat (propertize " " 'display (helm-imenu-icon-for-type type))
+                              " "
+                              (propertize disp1 'help-echo bufname 'types types))
            collect
            (cons disp (cons k v))))
 
```
How it looks:
Capture d’écran_2022-05-28_06-46-18

**Comment by taquangtrung** [comment]
Thanks! I'll update the code accordingly to your suggestion.

Btw, the `for` loop that set the typefaces of all elements in the `types` will reset also the documentation typeface returned by LSP mode (the last element of the `types` variable). This happens also in the old code.

```
           for disp1 = (mapconcat
                        (lambda (x)
                          (propertize
                           x 'face
                           (cl-loop for (p . f) in helm-imenu-type-faces
                                    when (string-match p x)
                                    do (setq type (match-string 0 x))
                                    and return f
                                    finally return 'default)))
                        types helm-imenu-delimiter)
```

In my previous patch, I fixed it by not modifying the typeface of `(cdr types)`.

I'll update also this in a new patch.

**Comment by taquangtrung** [comment]
I did try to use `all-the-icons` package but its icons looks quite ugly, compared to the icons from VSCode:

Here is the result using `all-the-icons` (the icons are ugly and not aligned with the text)

helm-imenu-all-the-icons

Here is the result using VSCode icons (the icons are pretty, aligned well with the text)

helm-imenu-vscode-icons

Do you think that we should still use VSCode icons? 

If you think that we shouldn't require `company`, how about creating a local copy of VSCode icons in the Helm package?

**Comment by taquangtrung** [comment]
I updated the code so that the icons are vertically aligned with the text (but they will still have problems with horizontal alignment, if the icons' width are sort).

The result now looks better:

helm-imenu

But there are many icons for source code items that are missing from `all-the-icons`.

Compared to that, VSCode has a full set of icons for source code items: https://github.com/microsoft/vscode-icons

Can you advise how to go ahead?

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> I did try to use all-the-icons package but its icons looks quite ugly, compared to the icons from VSCode:
>
> Here is the result using all-the-icons (the icons are ugly and not aligned with the text)
>
> helm-ime
>
> Here is the result using VSCode icons (the icons are pretty, aligned well with the text)
>
> helm-ime
>
> Do you think that we should still use VSCode icons?
>
> If you think that we shouldn't require company, how about creating a
> local copy of VSCode icons in the Helm package?

Isn't there copyright issues doing this?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> I updated the code so that the icons are vertically aligned with the text (but they will still have problems with horizontal alignment, if the icons' width are sort).
>
> The result now looks better:
>
> helm-ime

Looks good, however some comments:

I would like to keep the information between icon and symbol name with
separator i.e. <icon> Function/foo.

When using (concat icon text) preselection will fail because the icon is
part of the matched text, it is better probably to use 
    (concat (propertize " " 'display icon) " " text)
the space will cause less problems, otherwise we have to use a regexp
like in helm-find-files (helm-ff-last-expanded-candidate-regexp) to
match the icon.

> But there are many icons for source code items that are missing from
> all-the-icons.

Is there a standard for such icons? If not, probably we can use any icons
available in all-the-icons (what I did in my example code).
To choose icons you can use helm-all-the-icons.el:
https://github.com/emacs-helm/helm-all-the-icons

-- 
Thierry

**Comment by taquangtrung** [comment]
Thanks!

> Looks good, however some comments: I would like to keep the information between icon and symbol name with separator i.e. <icon> Function/foo. 

I can do that. Originally, I want to replace the symbol name `Function` by the icon to save some space (I'm writing Rust code, and the namespace are usually long). 

Currently, I use a boolean variable `helm-imenu-show-item-type-name` to control whether to print the text `Function`. 
If it is set to `t`, then the both the icon and the symbol name will be displayed.


> When using (concat icon text) preselection will fail because the icon is part of the matched text, it is better probably to use (concat (propertize " " 'display icon) " " text) the space will cause less problems, otherwise we have to use a regexp like in helm-find-files (helm-ff-last-expanded-candidate-regexp) to match the icon.

I think in the latest patch, I already use `(propertize " " 'display type-icon)` like what you suggested.

> But there are many icons for source code items that are missing from all-the-icons.
> Is there a standard for such icons? If not, probably we can use any icons available in all-the-icons (what I did in my example code). To choose icons you can use helm-all-the-icons.el: https://github.com/emacs-helm/helm-all-the-icons
> […](#)

Thanks! I'll use this package to look through `all-the-icons`. Previously I have to look up in the internet, and it's very time consuming.

Btw, why isn't it published in Melpa?

**Comment by taquangtrung** [comment]
@thierryvolpiatto: I encountered the following errors when using `helm-all-the-icons`:

```
Error running timer: (wrong-type-argument buffer-or-string-p ("wave-right" . ""))
Error running timer: (wrong-type-argument buffer-or-string-p ("javascript-shield" . ""))
Error running timer: (wrong-type-argument buffer-or-string-p ("javascript-badge" . ""))
```

Do you know where does the error come from?

I'm also investigating it, but haven't got any clue yet.

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> @thierryvolpiatto: I encountered the following errors when using helm-all-the-icons:
>
> Error running timer: (wrong-type-argument buffer-or-string-p ("wave-right" . ""))
> Error running timer: (wrong-type-argument buffer-or-string-p ("javascript-shield" . ""))
> Error running timer: (wrong-type-argument buffer-or-string-p ("javascript-badge" . ""))
>
> Do you know where does the error come from?

No idea, I have no error here.
Do you have custom settings for all-the icons?

>
>
> I'm also investigating it, but haven't got any clue yet.

Perhaps if you can have a backtrace? 

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by taquangtrung** [comment]
That issue is due to the call to `get-text-property` caused by `helm-score-candidate-for-pattern` in `helm-core.el`.

In the specs of `get-text-property`, it says that "OBJECT should be a buffer or a string", but here it's a cons object `("wave-right" . "")`.

I didn't modify `all-the-icons` package. Not sure why the error doesn't occur with you.

```
Debugger entered--Lisp error: (wrong-type-argument buffer-or-string-p ("wave-right" . ""))
  get-text-property(0 display ("wave-right" . ""))
  (equal (get-text-property 0 'display candidate) "[?]")
  (if (equal (get-text-property 0 'display candidate) "[?]") 200.0 (funcall helm-fuzzy-default-score-fn candidate pattern))
  helm-score-candidate-for-pattern(("wave-right" . "") "a")
  #f(compiled-function (s1 s2) #<bytecode -0x155f54404330f9f3>)((#("wave-right        " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "wave-right" . "") (#("wave-left         " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "wave-left" . ""))
  helm-fuzzy-matching-default-sort-fn-1(((#("apache            " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "apache" . "") (#("atom              " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "atom" . "") (#("aws               " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "aws" . "") (#("csharp            " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "csharp" . "") (#("csharp-line       " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "csharp-line" . "") (#("css3-alt          " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "css3-alt" . "") (#("dlang             " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "dlang" . "") (#("erlang            " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "erlang" . "") (#("haskell           " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "haskell" . "") (#("jasmine           " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "jasmine" . "") (#("java              " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "java" . "") (#("javascript        " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "javascript" . "") (#("javascript-badge  " 18 19 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "all-the-icons" :height 1.2) face (:family "all-the-icons" :height 1.2))) "javascript-badge" . "")) t)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16>(((#("apache            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "apache" . "") (#("atom              " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "atom" . "") (#("aws               " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "aws" . "") (#("csharp            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "csharp" . "") (#("csharp-line       " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "csharp-line" . "") (#("css3-alt          " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "css3-alt" . "") (#("dlang             " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "dlang" . "") (#("erlang            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "erlang" . "") (#("haskell           " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "haskell" . "") (#("jasmine           " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "jasmine" . "") (#("java              " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "java" . "") (#("javascript        " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "javascript" . "") (#("javascript-badge  " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "javascript-badge" . "")) ((name . "alltheicons") (candidates closure ((max-len . 17) (fn . all-the-icons-alltheicon) (data . all-the-icons-data/alltheicons-alist) t) nil (let* (... ... ... ... ... ...) (while ... ... ... ... ... ...) (nreverse --cl-var--))) (keymap keymap (67108905 . tddsg/helm-own-frame-enlarge-current-frame) (67108904 . tddsg/helm-own-frame-shrink-current-frame) (33554454 . helm-previous-page) (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap ...)) (help keymap (109 . helm-help)) (23 . #f(compiled-function () ... #<bytecode -0x803f6764240e029>)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8) (20) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap (111 . tddsg/helm-maybe-exit-minibuffer-other-window) (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (63 . helm-help) (110 . #f(compiled-function () ... #<bytecode -0x80021b5aa40e029>)) (108 . helm-display-line-numbers-mode) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-insert-or-copy) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (37 . helm-exchange-minibuffer-and-header-line) (95 . helm-toggle-full-frame) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) ...) (action ("insert icon" lambda (candidate) (let ... ...)) ("insert code for icon" lambda (candidate) (insert ...)) ("insert name" lambda (candidate) (insert ...)) ("insert raw icon" lambda (candidate) (insert ...)) ("kill icon" lambda (candidate) (let ... ...))) (requires-pattern . 0) (filtered-candidate-transformer #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16> helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match . t) (redisplay . identity) (header-line . #("C-j: insert icon (keeping sessio..." 0 3 (font-lock-face help-key-binding face help-key-binding))) (multimatch . t) (group . helm)))
  helm-apply-functions-from-source(((name . "alltheicons") (candidates closure (... ... ... t) nil (let* ... ... ...)) (keymap keymap (67108905 . tddsg/helm-own-frame-enlarge-current-frame) (67108904 . tddsg/helm-own-frame-shrink-current-frame) (33554454 . helm-previous-page) (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode -0x803f6764240e029>)) (f1 lambda nil ... ...) (8) ...) (action ("insert icon" lambda ... ...) ("insert code for icon" lambda ... ...) ("insert name" lambda ... ...) ("insert raw icon" lambda ... ...) ("kill icon" lambda ... ...)) (requires-pattern . 0) (filtered-candidate-transformer #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16> helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match . t) (redisplay . identity) (header-line . #("C-j: insert icon (keeping ..." 0 3 ...)) (multimatch . t) (group . helm)) (#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16> helm-fuzzy-highlight-matches) ((#("apache            " 18 19 ...) "apache" . "") (#("atom              " 18 19 ...) "atom" . "") (#("aws               " 18 19 ...) "aws" . "") (#("csharp            " 18 19 ...) "csharp" . "") (#("csharp-line       " 18 19 ...) "csharp-line" . "") (#("css3-alt          " 18 19 ...) "css3-alt" . "") (#("dlang             " 18 19 ...) "dlang" . "") (#("erlang            " 18 19 ...) "erlang" . "") (#("haskell           " 18 19 ...) "haskell" . "") (#("jasmine           " 18 19 ...) "jasmine" . "") (#("java              " 18 19 ...) "java" . "") (#("javascript        " 18 19 ...) "javascript" . "") (#("javascript-badge  " 18 19 ...) "javascript-badge" . "")) ((name . "alltheicons") (candidates closure (... ... ... t) nil (let* ... ... ...)) (keymap keymap (67108905 . tddsg/helm-own-frame-enlarge-current-frame) (67108904 . tddsg/helm-own-frame-shrink-current-frame) (33554454 . helm-previous-page) (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode -0x803f6764240e029>)) (f1 lambda nil ... ...) (8) ...) (action ("insert icon" lambda ... ...) ("insert code for icon" lambda ... ...) ("insert name" lambda ... ...) ("insert raw icon" lambda ... ...) ("kill icon" lambda ... ...)) (requires-pattern . 0) (filtered-candidate-transformer #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16> helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match . t) (redisplay . identity) (header-line . #("C-j: insert icon (keeping ..." 0 3 ...)) (multimatch . t) (group . helm)))
  helm-process-filtered-candidate-transformer(((#("apache            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "apache" . "") (#("atom              " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "atom" . "") (#("aws               " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "aws" . "") (#("csharp            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "csharp" . "") (#("csharp-line       " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "csharp-line" . "") (#("css3-alt          " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "css3-alt" . "") (#("dlang             " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "dlang" . "") (#("erlang            " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "erlang" . "") (#("haskell           " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "haskell" . "") (#("jasmine           " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "jasmine" . "") (#("java              " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "java" . "") (#("javascript        " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "javascript" . "") (#("javascript-badge  " 18 19 (rear-nonsticky t display ... font-lock-face ... face ...)) "javascript-badge" . "")) ((name . "alltheicons") (candidates closure ((max-len . 17) (fn . all-the-icons-alltheicon) (data . all-the-icons-data/alltheicons-alist) t) nil (let* (... ... ... ... ... ...) (while ... ... ... ... ... ...) (nreverse --cl-var--))) (keymap keymap (67108905 . tddsg/helm-own-frame-enlarge-current-frame) (67108904 . tddsg/helm-own-frame-shrink-current-frame) (33554454 . helm-previous-page) (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap ...)) (help keymap (109 . helm-help)) (23 . #f(compiled-function () ... #<bytecode -0x803f6764240e029>)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8) (20) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap (111 . tddsg/helm-maybe-exit-minibuffer-other-window) (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (63 . helm-help) (110 . #f(compiled-function () ... #<bytecode -0x80021b5aa40e029>)) (108 . helm-display-line-numbers-mode) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-insert-or-copy) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (37 . helm-exchange-minibuffer-and-header-line) (95 . helm-toggle-full-frame) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) ...) (action ("insert icon" lambda (candidate) (let ... ...)) ("insert code for icon" lambda (candidate) (insert ...)) ("insert name" lambda (candidate) (insert ...)) ("insert raw icon" lambda (candidate) (insert ...)) ("kill icon" lambda (candidate) (let ... ...))) (requires-pattern . 0) (filtered-candidate-transformer #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_16> helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match . t) (redisplay . identity) (header-line . #("C-j: insert icon (keeping sessio..." 0 3 (font-lock-face help-key-binding face help-key-binding))) (multimatch . t) (group . helm)))
```

**Comment by taquangtrung** [comment]
@thierryvolpiatto: I fixed that issue by patching `helm-score-candidate-for-pattern` in `helm-core.el`:

``` emacs-lisp
(defun helm-score-candidate-for-pattern (candidate pattern)
  "Assign score to CANDIDATE according to PATTERN."
  ;; Unknown candidates always go on top.
  (condition-case ex
    (if (equal (get-text-property 0 'display candidate) "[?]")
        200.00
      (funcall helm-fuzzy-default-score-fn candidate pattern))
    ('error 200.00)))
```

Do you think it's worth a PR?

**Comment by taquangtrung** [comment]
@thierryvolpiatto: I updated all the icons. 

Can you take a look at the PR to check if it is OK?

**Comment by thierryvolpiatto** [comment]
Thanks for the backtrace.

Ta Quang Trung ***@***.***> writes:

> That issue is due to the call to get-text-property caused by helm-score-candidate-for-pattern in helm-core.el.
>
> In the specs of get-text-property, it says that "OBJECT should be a buffer or a string", but here it's a cons object ("wave-right" . "").
>
> I didn't modify all-the-icons package. Not sure why the error doesn't occur with you.

Don't know either, will investigate.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> @thierryvolpiatto: I fixed that issue by patching helm-score-candidate-for-pattern in helm-core.el:
>
> (defun helm-score-candidate-for-pattern (candidate pattern)
>   "Assign score to CANDIDATE according to PATTERN."
>   ;; Unknown candidates always go on top.
>   (condition-case ex
>     (if (equal (get-text-property 0 'display candidate) "[?]")
>         200.00
>       (funcall helm-fuzzy-default-score-fn candidate pattern))
>     ('error 200.00)))
>
> Do you think it's worth a PR?

No thanks, this would hide the bug, I want to know first why you hit
this bug and not me.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> That issue is due to the call to get-text-property caused by helm-score-candidate-for-pattern in helm-core.el.
>
> In the specs of get-text-property, it says that "OBJECT should be a buffer or a string", but here it's a cons object ("wave-right" . "").
>
> I didn't modify all-the-icons package. Not sure why the error doesn't occur with you.

The reason is that for some reasons fuzzy-matching is enabled whereas it
should not.
 
-- 
Thierry

**Comment by taquangtrung** [comment]
> The reason is that for some reasons fuzzy-matching is enabled whereas it should not.

Oh I see. Thank you for the update. I'm using Spacemacs and it enables helm-fuzzy-matching by default.

Here are what I just found:

https://github.com/syl20bnr/spacemacs//blob/develop/layers/+spacemacs/spacemacs-completion/config.el#L27

https://github.com/syl20bnr/spacemacs//blob/develop/layers/+completion/helm/README.org#enable-fuzzy-searching-in-helm-buffers

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

>     The reason is that for some reasons fuzzy-matching is enabled whereas it should not.
>    
> Oh I see. Thank you for the update. I'm using Spacemacs and it enables helm-fuzzy-matching by default.

Why I always recommend not using Spacemacs.
Anyway it is fixed in helm-command.el.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Let me know when it will be ready to merge, thanks.

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> The PR is ready to be merged now. I have updated the icons according to what the current all-the-icons has.
>
> I also created an issue to its repository: domtronn/all-the-icons.el#321
>
> When they support new suitable icons, I'll create a new PR to update them.

Great thanks, now merged.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I made several changes, have a look.

**Comment by thierryvolpiatto** [comment]
Now need to fix helm-imenu-next-or-previous-section and we are done.

**Comment by taquangtrung** [comment]
The changes look good!

I ran `helm-imenu-next-section` and encountered this error:

```
condition-case: Wrong type argument: window-live-p, nil
```

It was caused by the command `with-helm-window` below:

```
(defun helm-imenu-next-or-previous-section (n)
  (with-helm-window
  ...
```

Is it the same error that you encountered?

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> The changes look good!
>
> I ran helm-imenu-next-section and encountered this error:
>
> condition-case: Wrong type argument: window-live-p, nil
>
> It was caused by the command with-helm-window below:
>
> (defun helm-imenu-next-or-previous-section (n)
>   (with-helm-window
>   ...
>
> Is it the same error that you encountered?

I didn't have an error, it is just not working, I will fix it ASAP.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> @thierryvolpiatto: I fixed that issue by patching helm-score-candidate-for-pattern in helm-core.el:
>
> (defun helm-score-candidate-for-pattern (candidate pattern)
>   "Assign score to CANDIDATE according to PATTERN."
>   ;; Unknown candidates always go on top.
>   (condition-case ex
>     (if (equal (get-text-property 0 'display candidate) "[?]")
>         200.00
>       (funcall helm-fuzzy-default-score-fn candidate pattern))
>     ('error 200.00)))
>
> Do you think it's worth a PR?

I found it. I guess you are calling helm-all-the-icons from helm-M-x and
you are using some code to set :fuzzy-match in its source, if so I could
reproduce the bug.
helm-M-x is let-bounding helm-fuzzy-sort-fn and when it exits it doesn't
have the time to restore so the let-bounded value is still used in the next
helm command, it is fixed now on master.

-- 
Thierry

**Comment by taquangtrung** [comment]
> Ta Quang Trung ***@***.***> writes:
> @thierryvolpiatto: I fixed that issue by patching helm-score-candidate-for-pattern in helm-core.el: (defun helm-score-candidate-for-pattern (candidate pattern) "Assign score to CANDIDATE according to PATTERN." ;; Unknown candidates always go on top. (condition-case ex (if (equal (get-text-property 0 'display candidate) "[?]") 200.00 (funcall helm-fuzzy-default-score-fn candidate pattern)) ('error 200.00))) Do you think it's worth a PR?
> I found it. I guess you are calling helm-all-the-icons from helm-M-x and you are using some code to set :fuzzy-match in its source, if so I could reproduce the bug. helm-M-x is let-bounding helm-fuzzy-sort-fn and when it exits it doesn't have the time to restore so the let-bounded value is still used in the next helm command, it is fixed now on master.
> […](#)
> -- Thierry

Thanks for the update! I just upgrade Helm recently and saw your new commits related to the fuzzy match.

Just FYI, I'm using Spacemacs, and I think it binds `helm-fuzzy-matching-highlight-fn` to `'helm-flx-fuzzy-highlight-match` (a function from https://github.com/PythonNut/helm-flx). This causes a new issue when running Helm:

Here is the error message my Spacemacs throws:

```
Error running timer: (wrong-number-of-arguments #<subr helm-flx-fuzzy-highlight-match> 4) [5 times]
```

I had to manually bind `helm-fuzzy-matching-highlight-fn` to `'helm-fuzzy-default-highlight-match` again so that Helm can work normally.

**Comment by thierryvolpiatto** [comment]
> Just FYI, I'm using Spacemacs, and I think it binds
> helm-fuzzy-matching-highlight-fn to 'helm-flx-fuzzy-highlight-match (a
> function from https://github.com/PythonNut/helm-flx). This causes a
> new issue when running Helm:
>
> Here is the error message my Spacemacs throws:
>
> Error running timer: (wrong-number-of-arguments #<subr helm-flx-fuzzy-highlight-match> 4) [5 times]

Yes, helm-fuzzy-matching-highlight-fn expects now a function with a
different signature, see commit 45d3360a.

-- 
Thierry

**Pull request merged**
