### PR TITLE
Overhaul emacs-helm.sh

### PR DESCRIPTION
**Pull request by Ambrevar**
Please review:
- There might be a good reason for the `2` exit code instead of `1`.
- Why was `helm-M-x` set differently?

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Please review:
>
>   * There might be a good reason for the 2 exit code instead of 1.

No particualr reason AFAIR

>   * Why was helm-M-x set differently?

No problem to remap instead of global binding M-x.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Please review:
>
>   * There might be a good reason for the 2 exit code instead of 1.

No particualr reason AFAIR

>   * Why was helm-M-x set differently?

No problem to remap instead of global binding M-x.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Please review:
>
>   * There might be a good reason for the 2 exit code instead of 1.

I finally had time to read the bash documentation of exit codes:

   All of the Bash builtins return an exit status of zero if they
succeed and a non-zero status on failure, so they may be used by the
conditional and list constructs.  All builtins return an exit status of
2 to indicate incorrect usage.

This is why I used 2, which is correct IMO.

-- 
Thierry

**Comment by Ambrevar** [comment]
1. Your script is a script, not a Bash built-in.
2. It's not Bash anymore :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>  1. Your script is a script, not a Bash built-in.
>  2. It's not Bash anymore :)

Perhaps, but I guess the conventions (posix?) for exit are not much different
between sh and bash, isn't it?

-- 
Thierry

**Comment by Ambrevar** [comment]
Regardless. Built-ins (`test`, etc.) return some error code:  There is no reason `emacs-helm.sh` should return the same error code as built-ins.  We are talking orange and bananas here.  `emacs-helm.sh` is a program, and like any Unix program it should return 0 on success, or _its own convention of exit codes_ on error.  If the exit codes don't matter, leave them to 1.  There is no good reason to puzzle the contributors by skipping 1.

**Comment by Ambrevar** [comment]
For future reference: A quick look at the dash(1) man page seems to show no mention of the `2` exit code.
A quick practical test (`test -ne 1; echo $?`) return 2, so it could be POSIX.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Regardless. Built-ins (test, etc.) return some error code: There is no
> reason emacs-helm.sh should return the same error code as
> built-ins. We are talking orange and bananas here. emacs-helm.sh is a
> program, and like any Unix program it should return 0 on success, or
> its own convention of exit codes on error. If the exit codes don't
> matter, leave them to 1. There is no good reason to puzzle the
> contributors by skipping 1.

Thanks for explanations.


--
Thierry

**Pull request merged**
