### PR TITLE
README: Improve phrasing

### PR DESCRIPTION
**Pull request by Ambrevar**
The quality of Helm's documentation is somewhat deteriorated by its typos, style issues and grammatical mistakes.  It calls for some editing.
I can perform a quick editing-run of the main documentation files if you'd like.  Let me know.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
I do my best to provide good documentation, but indeed my English is not very good.
If you want to go through documentation and fix all these issues, you are very welcome.
Thanks.

**Comment by Ambrevar** [comment]
Will do.
You are welcome to question/comment any of my changes.

**Comment by Ambrevar** [comment]
Most importantly: is "helm" or "Helm"?  Shouldn't it be "Emacs-Helm" in the title of the README?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Most importantly: is "helm" or "Helm"? Shouldn't it be "Emacs-Helm" in
> the title of the README?

You are right, perhaps Emacs-Helm is better (if you think it is go
ahead).

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Will do.

Many thanks.

> You are welcome to question/comment any of my changes.

Sure I will.

-- 
Thierry

**Pull request merged**
