### PR TITLE
Remove helm buffer from buffer-list if buffer gets killed.

### PR DESCRIPTION
**Pull request by swhahn**
Hello,
this is my first attempt to contribute to helm, so please be patient.

I'm not sure if there is a reason not to remove  a killed helm-buffer from helm-buffers, but
helm-resume is complaining about a killed buffer. So here is my patch proposal.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Sorry but I don't know what you want to achieve here, can you describe what happen exactly with helm-resume.

**Comment by michael-heerdegen** [comment]
Maybe he is meaning this:

helm-buffers-list, kill any buffer, resume, delete initial input ==> (error "No buffer named [some buffer name]").

**Comment by swhahn** [comment]
Sorry for my poor explanation. If you go call helm e.g. helm-find-files, helm puts the helm buffer in the helm-buffers list, so you can call (C-u) helm-resume to resume. If you delete one of this buffers and try to resume, then helm-resume is comlaining about the missing buffer. My patch deletes a helm buffer from buffer-list if the buffer gets killed. That's all.

**Comment by thierryvolpiatto** [comment]
Ok merged, thanks.
That said, it is generally a bad idea to kill helm buffers.

**Comment by michael-heerdegen** [comment]
I don't know what problem this fixed, but the bug I described was not about helm buffers, and the patch didn't fix it.

I also don't understand why we need to push something into kill-buffer-hook to update an outdated buffer list copy while calling buffer-list comes with no cost.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Maybe he is meaning this:
>
> helm-buffers-list, kill any buffer, resume, delete initial input ==> (error "No buffer named [some buffer name]").

No it is not what his patch fixed, and BTW I can't reproduce the bug you
describe which is unrelated to this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I don't know what problem this fixed, but the bug I described was not
> about helm buffers, and the patch didn't fix it.
>
> I also don't understand why we need to push something into
> kill-buffer-hook to update an outdated buffer list copy while calling
> buffer-list comes with no cost.

No, you misunderstand what was fixed, it is unrelated to this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
>> Maybe he is meaning this:
>>
>> helm-buffers-list, kill any buffer, resume, delete initial input ==> (error "No buffer named [some buffer name]").
>
> No it is not what his patch fixed, and BTW I can't reproduce the bug you
> describe which is unrelated to this.

I have it, could reproduce, will fix soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I have it, could reproduce, will fix soon.

Seems you already did.  Thanks!

**Pull request merged**
