### PR TITLE
[#1442] Add `helm-version` var and command

### PR DESCRIPTION
**Pull request by xiongtx**
Address #1442.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

>   * [#1442] Add `helm-version` var and command

I would prefer a command that extract the version number, see
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el#L40

-- 
Thierry

**Comment by xiongtx** [comment]
When installing from MELPA, `helm-core-pkg.el`'s version number gets overwritten by the MELPA version, i.e. `"20170207.42"` instead of `"2.5.4"`.

I don't know which is more useful for bug reporting, but it's strange that `"2.5.4"` is nowhere to be found in  `helm-core` when installing from MELPA. In fact, you'll need to look in `helm-pkg.el` to find it.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> When installing from MELPA, helm-core-pkg.el's version number gets
> overwritten by the MELPA version, i.e. "20170207.42" instead of
> "2.5.4".

This is the reason why I have not already installed helm/version.

> I don't know which is more useful for bug reporting,

The only useful thing is to have the revision used, but most users are
installing from Melpa and have not this information, and the Melpa
version is giving no clues of what have been exactly pushed to Melpa at
this time.

> but it's strange that "2.5.4" is nowhere to be found in helm-core when
> installing from MELPA. In fact, you'll need to look in helm-pkg.el to
> find it.

I don't want to maintain a helm-version variable in helm if this is what
you are asking.

--
Thierry

**Comment by xiongtx** [comment]
Maybe just a `VERSION` file with a version string then?

**Comment by xiongtx** [comment]
What about putting the version number in the package header with the `Version` keyword? 

That seems to be the standard practice, and there's even an [`lm-version`](https://github.com/bbatsov/emacs-lisp-style-guide/issues/35) function to support it.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> What about putting the version number in the package header with the
> Version keyword?

We have two packages in one...
I don't like also the way package.el fetch information in source files
header, this is a practice of another age, the standard place should be
the *pkg.el files and they should be used instead of building another
*pkg.el file, I already submitted the idea to emacs but they still want
to use headers of source files.

> That seems to be the standard practice, and there's even an lm-version
> function to support it.

There is no standard practice actually to provide a version number in
packages.

--
Thierry

**Pull request closed without merging**
