### PR TITLE
migemo support for helm-moccur-action

### PR DESCRIPTION
**Pull request by tam17aki**

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks.

**Comment by thierryvolpiatto** [comment]
@momomo5717 Applied thanks.

**Comment by momomo5717** [comment]
@thierryvolpiatto Thank you for applying it!
Should I git rebase and push force at #1186?

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> @thierryvolpiatto Thank you for applying it!

Sorry I missed the full PR and applied just the diff referenced in
#1185 or the diff appeared before the PR on github, don't know.

> Should I git rebase and push force at #1186?

I am not sure it is safe to rebase+push force here, I generally use
merge in such situations (I use git-mergetool).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Should I git rebase and push force at #1186?

Ok, merged, please verify all your changes came in.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by momomo5717** [comment]
I'm so sorry. I will be more careful in future. 
Thank you for improving it!

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> I'm so sorry. I will be more careful in future.

I think what's happen is you submitted your PR at the same time I was
commiting! Rare but can happen ;-).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by momomo5717** [comment]
>I think what's happen is you submitted your PR at the same time I was
>commiting! Rare but can happen ;-).

Thank you for saying that.

Maybe, it took a lot of time for me to write English.
As you know, I'm not good at English. 

When I wrote the comment and send the PR, only the commit e1f8e81 had been merged.
So I was confused at that time.
This is the cause of that. 

So I must study English more and I will.
(But the evil procrastination says to me every day "Emacs is more fun than studying English.")

Thank you for your patience with my poor English.

I'm looking forward to your next magic!

Thank you.

**Comment by momomo5717** [comment]
Hi, @tam17aki 

I learn many things from your blog. Thank you for the useful information!

I'd like to ask your support.
Would you write the following information at your blog?

Now `helm-migemo-mode` supports the following:

+ kill ring
+ occur
+ moccur (Thank you for adding it!)
+ buffers
+ files (One space after a current path is needed to get candidates via migemo.)
+ file name history
+ recentf
+ minibuffer history
+ bookmarks

It would be helpful for migemo users if you'd request other sources.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Hi, @tam17aki
>
> I learn many things from your blog. Thank you for the useful information!
>
> I'd like to ask your support.
> Would you write the following information at your blog?
>
> Now helm-migemo-mode supports the following:
>
>   * kill ring
>   * occur
>   * moccur (Thank you for adding it!)
>   * buffers
>   * files (One space after a current path is needed to get candidates via migemo.)
>   * file name history
>   * recentf
>   * minibuffer history
>   * bookmarks
>
> It would be helpful for migemo users if you'd request other sources.

I have added an entry in helm wiki, feel free to edit and modify.

https://github.com/emacs-helm/helm/wiki#use-migemo-in-helm

BTW what is the address of tam17aki blog?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by momomo5717** [comment]
>I have added an entry in helm wiki, feel free to edit and modify.
> 
>https://github.com/emacs-helm/helm/wiki#use-migemo-in-helm

Thank you for the entry and improving! It's very helpful.

>BTW what is the address of tam17aki blog?

The link is here:  [link](http://qiita.com/ballforest/items/4db3d66df16d84a027d0)
It's written in Japanese. Thank you for the post!

Introduced first impression of `helm-migemo-mode`.
He said important thing is that now migemo can be used in helm with no installing helm-migemo.el,
and notified `helm-swoop` users that now `helm-swoop` couldn't use migemo
because of depending on helm-migemo.el.

I suppose it would be helpful if there are some doc to extend plug-in with migemo.
e.g. `helm-source-sync` can be used with migemo. (Sorry if my interpretation is mistaken.)

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

>     I have added an entry in helm wiki, feel free to edit and modify.
>    
>     https://github.com/emacs-helm/helm/wiki#use-migemo-in-helm
>    
> Thank you for the entry and improving! It's very helpful.
>
>     BTW what is the address of tam17aki blog?
>    
> The link is here: link
> It's written in Japanese.

Thanks, not very useful for me, but japanese users will appreciate to
have the link.

> Introduced first impression of helm-migemo-mode.  He said important
> thing is that now migemo can be used in helm with no installing
> helm-migemo.el, and notified helm-swoop users that now helm-swoop
> couldn't use migemo because of depending on helm-migemo.el.

Ok, note that now helm-(m)occur can behave like helm-swoop (just need to
configure it to do so).

> I suppose it would be helpful if there are some doc to extend plug-in
> with migemo.  e.g. helm-source-sync can be used with migemo. (Sorry if
> my interpretation is mistaken.)

Will add soon some examples in wiki.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request merged**
