### PR TITLE
Handle marked candidates in Find file other window

### PR DESCRIPTION
**Pull request by xuchunyang**
Fixes (#1212)

I wrote this base on helm buffer's `C-c o` (that is, `helm-switch-to-buffers`).

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Looks good except the error handling for number max of windows to split.

**Comment by xuchunyang** [comment]
Yes, I just realized that, actually, I only tested 1/2/3 candidates before. helm buffer's `C-c o` has the same limitation.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Yes, I just realized that, actually, I only tested 1/2/3 candidates
> before. helm buffer's C-c o has the same limitation.

See also `dired-simultaneous-find-file' which we are using in
`helm-find-file-or-marked'.

The point is if one marks a lot of files and then decides to do C-c o, at
best it will hang emacs, otherwise emacs will crash.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
> The point is if one marks a lot of files and then decides to do C-c o, at
> best it will hang emacs, otherwise emacs will crash.

I don't understand your meaning, how that can happen?

I don't notice any serious problem, I've just tried to open all 49 files in helm git repo with `C-c o`, emacs does open all files but just show me 4 windows of them (all files are opened successfully), it interrupts with the error from `split-window` call

```
split-window: Window #<window 157 on helm-apt.el> too small for splitting (2)
```

I think the error is clear to user and we don't have to handle this, just like typing too many `C-x 3` at a time. And `dired-simultaneous-find-file` works in a different way: it can usually show much more windows (10+ in my case) and once it finds there are too many files to open, it will just give it up without open any file so that `split-window` will not fail.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     The point is if one marks a lot of files and then decides to do C-c o, at
>     best it will hang emacs, otherwise emacs will crash.
>    
> I don't understand your meaning, how that can happen?

I guess I had problems in the past when I wrote helm-switch-to-buffers.

> I don't notice any serious problem, I've just tried to open all 49
> files in helm git repo with C-c o, emacs does open all files but just
> show me 4 windows of them (all files are opened successfully), it
> interrupts with the error from split-window call
>
> split-window: Window #<window 157 on helm-apt.el> too small for splitting (2)

Ok so let use that, we will see later if we need to handle errors
ourself.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Thanks, merged.

**Pull request merged**
