### PR TITLE
Fix byte compiler warnings

### PR DESCRIPTION
**Pull request by progfolio**
Similar motivation to #2342, but for all of helm's byte compiled files.
Should compile cleanly now.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks merged.
The `(require 'cl-macs)`  will be removed later as I will move the minibuffer stuff out of helm-config (it have nothing to do here, it belong to helm-misc).
Generally for all what is "cl-" prefixed function you can use cl-lib.

**Comment by thierryvolpiatto** [comment]
Helm was not compiling with emacs-26.3, fixed now.

**Comment by manuel-uberti** [comment]
Just an FYI, I see this while compiling now:
```
In toplevel form:
helm-types.el:40:1: Warning: value returned from (fboundp
    'eieio-declare-slots) is unused
```

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Just an FYI, I see this while compiling now:
>
> In toplevel form:
> helm-types.el:40:1: Warning: value returned from (fboundp
>     'eieio-declare-slots) is unused

Thanks, I removed the call to eieio-declare-slots, I have no warnings
here in both emacs-26.3 and master.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Same here. Thank you.

**Pull request merged**
