### PR TITLE
Missing ` in call to helm-acase.

### PR DESCRIPTION
**Pull request by cnoguera**

### CODE REVIEW

**Comment by cnoguera** [comment]
Sorry, I got distracted and didnt actually explain the reason for the pull request.
In [commit 0e3b0917ba29bb28826bf1d36fba53814b8ad3a6](https://github.com/emacs-helm/helm/commit/0e3b0917ba29bb28826bf1d36fba53814b8ad3a6), when helm-acase was introduced, the backquote was removed.  
I believe that for that reason, the expansion of the macro tries to eval "B", which in my case broke helm-mini.
Reintroducing the backquote fixed helm-mini for me.

**Comment by cnoguera** [comment]
Actually I cannot reproduce it anymore. It seems that indeed the problem was indeed the old .elc. 
That will teach me to ask before submitting a pull request. 

Please feel to close the pull request, and thanks for spending the time helping me out.

**Comment by thierryvolpiatto** [comment]
Thanks, closing now.

**Comment by thierryvolpiatto** [comment]
guoqinglei <notifications@github.com> writes:

> I do not know how to recompile helm. I reinstalled the helm many times, it still shows "Invalid function: B".
> But I have removed the *.elc files in the helm directories and restarted emacs, it works ok.
> Anybody can tell me how to recompile the helm? I am a starter of emacs for a few months.

How did you install helm, from source or from Melpa?

-- 
Thierry

**Comment by alphapapa** [comment]
> I do not know how to recompile helm. I reinstalled the helm many times, it still shows "Invalid function: B".
> But I have removed the *.elc files in the helm directories and restarted emacs, it works ok.
> Anybody can tell me how to recompile the helm? I am a starter of emacs for a few months.

The easiest way to fix this kind of problem is to delete the package in question and reinstall from scratch.  For example, if you installed it from MELPA, do `M-x package-delete RET helm RET`, then `M-x package-install RET helm RET`.  You may also need to do that for `helm-core`.

**Comment by stribb** [comment]
For me, it was simpler to run M-x package-reinstall RET helm RET.

The Helm ecosystem has become relatively large so there are a fair few dependencies on it nowadays. This obviates the need to remove everything and retrieve them.

**Pull request closed without merging**
