### PR TITLE
Fix helm-ucs for upcoming Emacs release

### PR DESCRIPTION
**Pull request by notetiene**
A new incompatible change is that ucs-names will be a hash-table
instead of a list.  See Emacs Bug#28302.

* helm-font.el (helm-calculate-ucs-alist-max-len): Add function to
calculate ucs-names candicates when wrapped inside a list.
(helm-calculate-ucs-hash-table-max-len): Add function to calculate
ucs-names candicates when wrapped inside a hash-table.
(helm-calculate-ucs-max-len): Refactor to support the hash-table.
(helm-ucs-collect-symbols-alist): Add function to collect the
ucs-names list.
(helm-ucs-collect-symbols-hash-table): Add function to collect the
ucs-names hash-table.
(helm-ucs-collect-symbols): Refactor to support the hash-table.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks, merged.

**Comment by thierryvolpiatto** [comment]
Just tried with emacs-26, will need some more filtering with new behavior.

**Comment by notetiene** [comment]
Do you mean with `helm-ucs` or in general?

I know for sure I could refactor the code merged to a simpler loop probably. However, I'm not really used to cl-loops.

**Comment by thierryvolpiatto** [comment]
Etienne <notifications@github.com> writes:

> Do you mean with helm-ucs or in general?

It is general, but it is not due to your recent changes, it was here but
I didn't see it, I found (with emacs-26 it popup in first position) that
"LINE FEED (LF)" is not printable (it represent "\n"), I removed it for
now as I don't think people needs helm-ucs to print "\n".

> I know for sure I could refactor the code merged to a simpler loop
> probably. However, I'm not really used to cl-loops.

Probably, but don't worrie of this I will do it if needed.

Thanks again for your work.

--
Thierry

**Pull request merged**
