### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by manuel-uberti**
Hi,

this is my attempt at doing something useful for Helm besides opening tickets. :)

I'd like to go through the docstrings in the Helm codebase and see if there is something to fix. This is not me saying Helm has a poor documentation. I'm not aiming at changing the documentation meaning and purpose at all. On the contrary, my intent is only to fix some grammar[1] and other minor things. 

This PR is not completed yet. I opened it as a work-in-progress to show what I have done so far and to understand if this is something welcomed so I can go on with it. I will update here when my work is ready.

Some questions before proceeding with my editing:

- Do you want me to apply filling to the docstrings?
- Do you want one or two spaces after a period? Emacs usually uses two spaces.
- How should the word "Helm" appear in the documentation? It seems to be spelled differently in various occasions: "Helm", "helm", "\`helm\`".

Let me know what you think. :)

[1] I am not an English native speaker, but I have a Cambridge Advanced English (Grade A) certificate. If you prefer an English native speaker for this, then I am not the right guy.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> DO NOT MERGE YET
>
> Hi,
>
> this is my attempt at doing something useful for Helm besides opening tickets. :)
>
> I'd like to go through the docstrings in the Helm codebase and see if there is something to fix. This is not me saying Helm has a poor documentation. I'm not aiming at
> changing the documentation meaning and purpose at all. On the contrary, my intent is only to fix some grammar[1] and other minor things.
>
> This PR is not completed yet. I opened it as a work-in-progress to
> show what I have done so far and to understand if this is something
> welcomed so I can go on with it.

More than welcome!

> I will update here when my work is ready.

Thanks.

> Some questions before proceeding with my editing:
>
>   • Do you want me to apply filling to the docstrings?

Yes, BUT, be careful when you fill (i.e. M-q) special characters at BOL
must be quoted otherwise we will have errors at compilation or the
docstring will not display properly.

>   • Do you want one or two spaces after a period? Emacs usually uses
>   two spaces.

Yes US people use two spaces, so lets use two spaces.

>   
>   • How should the word "Helm" appear in the documentation? It seems
>   to be spelled differently in various occasions: "Helm", "helm",
>   "`helm`".

Probably "Helm".

> Let me know what you think. :)
>
> [1] I am not an English native speaker, but I have a Cambridge
> Advanced English (Grade A) certificate. If you prefer an English
> native speaker for this, then I am not the right guy.

:-) At least your english will be far better than mine.

Let me know when your PR will be ready to merge, and if you have
questions aboout Helm don't hesitate.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
OK, @thierryvolpiatto, I think I pushed all my changes.

Please review them and if you need me to change anything, just yell at me. Helm is huge and the documentation just as big, so I'm pretty sure my work is not a definitive one. But hopefully it's a good start. :)

**Comment by thierryvolpiatto** [comment]
Just a small comment: Generally it is better to have the first sentence of docstrings on a single line, let me know if you have not the time to fix this I will merge and do it.
Thanks.

**Comment by manuel-uberti** [comment]
You're right, I see some of the docstring go beyond a single line. I didn't know how to rephrase them without losing the overall meaning, that's why I didn't change them.

**Comment by thierryvolpiatto** [comment]
Ok, merged, will correct the first lines of docstrings filled by error ASAP.
Thanks!

**Comment by manuel-uberti** [comment]
Great. I'm happy I could give something back to Helm. :)

**Pull request merged**
