### PR TITLE
Keep using a prompt even with truncated line in header-line (#1064).

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
* helm.el (helm--set-header-line): Do it.

### CODE REVIEW

**Comment by michael-heerdegen** [comment]
Tried it only shortly, will use it the whole day for testing.  Didn't look at the code yet.

My first impression is good.

But there are big problems.  The cursor vanishes for long inputs (when the [...] appeared) when hitting C-b.  When I hit C-f, I get an "end of buffer" error and the input is in nirvana.

Sometimes, the whole thing doesn't work.  If I hit C-f and keep pressing the "a" key, the minibuffer expands to multiple lines, and the header line doesn't show the [...] as expected.

Sometimes, I just get an error, and my input is gone.

**Comment by michael-heerdegen** [comment]
Sorry, that the [...] doesn't appear and as well as the expanding minibuffer was tested with the old code, Doesn't happen with yours.

**Comment by michael-heerdegen** [comment]
Another, minor, problem: if I just for testing, hit C-x C-f and keep hitting the "a" key, I see that after the ellipsis appeared, the second line will only hold a twenty chars or so until it is truncated again.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Tried it only shortly, will use it the whole day for testing. Didn't look at the code yet.
>
> My first impression is good.
>
> But there are big problems. The cursor vanishes for long inputs (when the [...] appeared) when hitting C-b. When I hit C-f, I get an "end of buffer" error and the
> input is in nirvana.
>
> Sometimes, the whole thing doesn't work. If I hit C-f and keep pressing the "a" key, the minibuffer expands to multiple lines, and the header line doesn't show the
> [...] as expected.
>
> Sometimes, I just get an error, and my input is gone.

Thanks for trying it.
Yes I have noticed all these problems and I have commited something
different, perhaps I will retain this new version, but let's try it
first.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Yes I have noticed all these problems and I have commited something
> different, perhaps I will retain this new version, but let's try it
> first.

Ok.  Yes, seems to work better indeed.

One thing: if I try "helm-eval-expression", you get no prompt at all
with that version, the header-line doesn't mirror the minibuffer, but
the minibuffer is hidden as well.  With other words, you don't see what
you type, nowhere.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Yes I have noticed all these problems and I have commited something
>> different, perhaps I will retain this new version, but let's try it
>> first.
>
> Ok. Yes, seems to work better indeed.

Good thanks.

> One thing: if I try "helm-eval-expression", you get no prompt at all
> with that version, the header-line doesn't mirror the minibuffer, but
> the minibuffer is hidden as well. With other words, you don't see what
> you type, nowhere.

It is fixed, I guess you have just evaled helm--set-header-line, load
the whole file instead or eval helm-read-pattern-maybe (or reinstall).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> One thing: if I try "helm-eval-expression", you get no prompt at all
> with that version, the header-line doesn't mirror the minibuffer, but
> the minibuffer is hidden as well.  With other words, you don't see what
> you type, nowhere.

Oops - that's my own fault, of course.  I was testing with an outdated
version of my `helm-hide-minibuffer-maybe'.  Forget this.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Michael Heerdegen <michael_heerdegen@web.de> writes:
>
>> One thing: if I try "helm-eval-expression", you get no prompt at all
>> with that version, the header-line doesn't mirror the minibuffer, but
>> the minibuffer is hidden as well. With other words, you don't see what
>> you type, nowhere.
>
> Oops - that's my own fault, of course. I was testing with an outdated
> version of my `helm-hide-minibuffer-maybe'. Forget this.

Ok, do you think this version is good enough to merge ?
You will be able to change details later if you want (face, sign ...).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
BTW You have now write access to helm repo, you can create branches,
make changes etc ... (be careful ;-).
Of course you can still make PR from your fork, but you have better time
to make a new branch and make the PR from this branch.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> BTW You have now write access to helm repo, you can create branches,
> make changes etc ... (be careful ;-).  Of course you can still make PR
> from your fork, but you have better time to make a new branch and make
> the PR from this branch.

Ok, thanks.  I'll first have a look at the links github sent me as a
side affect.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Ok, do you think this version is good enough to merge ?

I think so, the defun is more or less finished.

Question: Would you prefer adding "helm-hide-minibuffer-maybe" to the
hook by default?  We could make "helm-echo-input-in-header-line" accept
three values (one more meaning "show in header line and hide
minibuffer"), or add a new var controlling this.  Then users not
mastering Elisp would be able to use this feature.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Ok, do you think this version is good enough to merge ?
>
> I think so, the defun is more or less finished.

Ok, you can perhaps merge yourself the PR (click on the button) to see
if all works well.

> Question: Would you prefer adding "helm-hide-minibuffer-maybe" to the
> hook by default? We could make "helm-echo-input-in-header-line" accept
> three values (one more meaning "show in header line and hide
> minibuffer"), or add a new var controlling this. Then users not
> mastering Elisp would be able to use this feature.

Ok for this, go ahead.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Ok for this, go ahead.

Sorry, I was short on time the last days, and will be on a tour soon.
I'll do this ASAP.  I should be online on the trip, unless I have bad
luck.

FWIW, this is the current version of the defun that should go to
"helm-minibuffer-set-up-hook":

  (defun helm-hide-minibuffer-maybe ()
    "Hide minibuffer contents in a Helm session.
This function should normally go to `helm-minibuffer-set-up-hook'.
It has no effect if `helm-echo-input-in-header-line' is nil."
    (when (buffer-local-value 'helm-echo-input-in-header-line
                              (get-buffer (helm-buffer-get)))
      (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
        (overlay-put ov 'window (selected-window))
        (overlay-put ov 'face (let ((bg-color (face-background 'default nil)))
                                `(:background ,bg-color :foreground ,bg-color)))
        (setq-local cursor-type nil))))

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Ok for this, go ahead.
>
> Sorry, I was short on time the last days, and will be on a tour soon.
> I'll do this ASAP. I should be online on the trip, unless I have bad
> luck.
>
> FWIW, this is the current version of the defun that should go to
> "helm-minibuffer-set-up-hook":

Thanks, added with small modifications.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thanks.

**Pull request merged**
