### PR TITLE
* doc/{helm.org, helm-manual-1.org}: Re-arrange

### PR DESCRIPTION
**Pull request by rnchzn**
* doc/{helm.org, helm-manual-1.org}: Re-arrange
    * doc/helm-classes.org: New
    * doc/Makefile: Add doc/helm-classes.org

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks, merged, I will have a look at helm-classes.org, note that many infos are already provided in helm-devel.org.
Also I noticed that many helm-info* commands are not working, last time I checked only helm-info-helm-manual-1 was working, any ideas?

**Comment by thierryvolpiatto** [comment]
Update: make info failed:

```
  2 make info 
emacs -q -batch -L . -l doc/ox-texinfo.el  --file=doc/helm-manual-1.org --eval '(org-texinfo-export-to-texinfo)'
makeinfo --no-split doc/helm-manual-1.texi -o doc/helm-manual-1.info
doc/helm-manual-1.texi:373: warning: could not find @image file `./helm-M-x.txt' nor alternate text
emacs -q -batch -L . -l doc/ox-texinfo.el  --file=doc/helm-manual.org --eval '(org-texinfo-export-to-texinfo)'
makeinfo --no-split doc/helm-manual.texi -o doc/helm-manual.info
emacs -q -batch -L . -l doc/ox-texinfo.el  --file=doc/helm.org --eval '(org-texinfo-export-to-texinfo)'
makeinfo --no-split doc/helm.texi -o doc/helm.info
emacs -q -batch -L . -l doc/ox-texinfo.el  --file=doc/helm-classes.org --eval '(org-texinfo-export-to-texinfo)'
Unable to read file "/home/rameshnedunchezian/src/helm/doc/doc-setup.org"
Unable to read file "/home/rameshnedunchezian/src/helm/doc/doc-setup.org"
Unable to read file "/home/rameshnedunchezian/src/helm/doc/doc-setup.org"
Undefined Org macro: kbd; aborting
Makefile:117: recipe for target 'doc/helm-classes.texi' failed
make: *** [doc/helm-classes.texi] Error 255
```
Looks it is again some hardcoded paths, nothing difficult to fix IMO.

**Comment by thierryvolpiatto** [comment]
From what I can see, there is a lot of duplicates in classes documentation because each classes have helm-source as parent and share BTW the same slots, perhaps we should document these slots only once in helm-source documentation (unless a class is using a specific value for a slot e.g. helm-source-in-buffer uses a specific value for `:candidates`).

**Comment by rnchzn** [comment]
> Update: make info failed:

> From what I can see, there is a lot of duplicates in classes documentation because each classes have helm-source as parent and share BTW the same slots, perhaps we should document these slots only once in helm-source documentation (unless a class is using a specific value for a slot e.g. helm-source-in-buffer uses a specific value for :candidates).

Both of these are fixed in https://github.com/emacs-helm/helm/pull/2408

> Also I noticed that many helm-info* commands are not working, last time I checked only helm-info-helm-manual-1 was working, any ideas?

`helm.org` and `helm-classes.org` are the main info files. They have indices enabled.  Other files are imported from existing `org` files like `M-x helm-documentation` or from the Wiki.  They didn't have indices to begin with.  I might have temporarily added indices to these other files, to temporarily give you a feel for what is  to come.

See 

```
(info "(helm) Commands in keymap helm-command-map")

(info "(helm) Commands in keymap helm-find-files-map")

(info "(helm) Commands in keymap helm-buffer-map")

(info "(helm-classes) class helm-source")

```

**Comment by thierryvolpiatto** [comment]
Ramesh Nedunchezian ***@***.***> writes:

>     Update: make info failed:
>    
>     From what I can see, there is a lot of duplicates in classes documentation because each classes have helm-source as parent and share BTW the same slots, perhaps we should document
>     these slots only once in helm-source documentation (unless a class is using a specific value for a slot e.g. helm-source-in-buffer uses a specific value for :candidates).
>    
> Both of these are fixed in #2408
>
>     Also I noticed that many helm-info* commands are not working, last time I checked only helm-info-helm-manual-1 was working, any ideas?
>    
> helm.org and helm-classes.org are the main info files. They have indices enabled. Other files are imported from existing org files like M-x helm-documentation or from the Wiki. They didn't
> have indices to begin with. I might have temporarily added indices to these other files, to temporarily give you a feel for what is to come.
>
> See
>
> (info "(helm) Commands in keymap helm-command-map")
>
> (info "(helm) Commands in keymap helm-find-files-map")
>
> (info "(helm) Commands in keymap helm-buffer-map")
>
> (info "(helm-classes) class helm-source")

Ok thanks I will look soon into this.

-- 
Thierry

**Pull request merged**
