### PR TITLE
Two very trivial fixes

### PR DESCRIPTION
**Pull request by xuchunyang**
Feel free to correct me if I am wrong.

### CODE REVIEW

**Comment by michael-heerdegen** [comment]
FWIW, I would prefer to switch to `helm-completing-read-symbols' internally whenever the second argument to `completing-read' is `eq' to (the value of) `obarray'.  Thierry didn't like the idea, though.  It's not perfect, but I  think it would still be better than a hardcoded whitelist of command names.  We could also combine the two methods.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Feel free to correct me if I am wrong.

>   * Remove unused variable helm-M-x-input-history

It is unused indeed, but if it is here, it is I used it in the past and
just forgot to reenable it, can't remember.
No body complained about this, but perhaps it is a good thing to
reenable ?
It is used when you use M-p, actually we have minibuffer-history in M-x
which send unrelated stuff for M-x.
If you want to reenable it in this PR, add it to :input-history.

>   * Use helm-completing-read-symbols for disassemble

Ok for this one, but perhaps we should follow Michael advice for this
and use it inconditionally when we find an obarray.
But lets go like this for now ;-).

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> FWIW, I would prefer to switch to helm-completing-read-symbols'
> internally whenever the second argument tocompleting-read' is eq' to
> (the value of)obarray'. Thierry didn't like the idea, though. It's not
> perfect, but I think it would still be better than a hardcoded
> whitelist of command names. We could also combine the two methods.

I am not against, I am just reluctant to such changes when not really
necessary, but yes perhaps we should do this at some point.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Chunyang Xu <notifications@github.com> writes:
>
>> Feel free to correct me if I am wrong.
>
>>   * Remove unused variable helm-M-x-input-history
>
> It is unused indeed, but if it is here, it is I used it in the past and
> just forgot to reenable it, can't remember.

I looked in git history and couldn't find it.
I think I added the variable with the intention of using it in the
helm-comp-read of helm-M-x and always forgot to bind it argh!

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
I don't like my approach much, too, but I think it's the best we can currently do.  Of course could we handle the case more generally, e.g. via a `obarrayp' test, and handle arbitrary obarrays.

**Comment by xuchunyang** [comment]
> It is unused indeed, but if it is here, it is I used it in the past and
> just forgot to reenable it, can't remember.
> No body complained about this, but perhaps it is a good thing to
> reenable ?
> It is used when you use M-p, actually we have minibuffer-history in M-x
> which send unrelated stuff for M-x.
> If you want to reenable it in this PR, add it to :input-history.

Done in a7eee27

**Comment by thierryvolpiatto** [comment]
Thanks, merged.

**Pull request merged**
