### PR TITLE
Fix issue #1467 (fix handling buffers with nil default-directory)

### PR DESCRIPTION
**Pull request by CyberShadow**
This fixes it for me.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Merged but IMO this should be fixed upstream.

**Comment by thierryvolpiatto** [comment]
Thanks.

**Comment by CyberShadow** [comment]
I agree, unfortunately as it's difficult to reproduce and analyze, it's difficult to find its source.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> I agree, unfortunately as it's difficult to reproduce and analyze,
> it's difficult to find its source.

Perhaps report the bug to emacs ?

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by CyberShadow** [comment]
What use is a bug report without solid reproduction instructions? I was wrong to report it to helm in the first place, because I twice thought it could be easily reproduced, and twice I was wrong.

Considering that no one encountered it before me, it's probably caused by another package (or possibly even something in my `init.el`).

**Pull request merged**
