### PR TITLE
'helm-symbol-completion-table-affixation', fix 'make-string' error

### PR DESCRIPTION
**Pull request by karbiv**
C-h f, `describe-function` in Helm throws an error on candidates with long symbol class prefixes, like "c-v'*-" (6 chars).

How to reproduce:
C-h f
input "yas/minor-mode"
`helm-completion-style` custom variable is default, `'helm`.

What causes the error:
`yas/minor-mode` symbol class shown as prefix is "c-v'*-" :
" c " command
" - " obsolete, `'byte-obsolete-info`
" v " var, not a defcustom
" ' " `local-variable-if-set-p`
" * " not default value if buffer local
" - " `'byte-obsolete-variable`

`help--symbol-class` currently can return at most 8 characters long symbol class.
This line in `helm-symbol-completion-table-affixation` causes the error:

```
(propertize
    " " 'display (concat it (make-string (- 5 (length it)) ? )))
```
`make-string` here gets negative number argument on candidates with long symbol classes.

### CODE REVIEW

**Comment by karbiv** [comment]
PR aligns candidates with long prefixes like this:
Screenshot from 2024-03-27 10-17-14

So function names are shifted, but only for very rare functions with long prefixes. Almost all functions don't have prefixes longer than 2 characters, and Helm buffer looks as usual.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> C-h f, describe-function in Helm throws an error on candidates with long symbol class prefixes, like "c-v'*-" (6 chars).
>
> How to reproduce:
> C-h f
> input "yas/minor-mode"
> helm-completion-style custom variable must be defailt, 'helm.
>
> What causes the error:
> yas/minor-mode symbol class shown as prefix is "c-v'*-" :

From which package yas/minor-mode is coming?
I tried installing yasnippet package and it doesn't provide such symbol,
it provide yas-minor-mode with "c" as prefix.
Maybe your yasnippet package is not up to date?

> 
> " c " command " - " obsolete, 'byte-obsolete-info " v " var, not a
> defcustom " ' " local-variable-if-set-p " * " not default value if
> buffer local " - " 'byte-obsolete-variable
>
> help--symbol-class currently can return at most 8 characters long symbol class.
> This line in helm-symbol-completion-table-affixation causes the error:
>
> (propertize
>     " " 'display (concat it (make-string (- 5 (length it)) ? )))
>
> make-string here gets negative number argument on candidates with long symbol classes.
>
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/emacs-helm/helm/pull/2656
>
> Commit Summary
>
>   • e70dbcb 'helm-symbol-completion-table-affixation', fix 'make-string' error
>
> File Changes
>
> (1 file)
>
>   • M helm-mode.el (29)
>
> Patch Links:
>
>   • https://github.com/emacs-helm/helm/pull/2656.patch
>   • https://github.com/emacs-helm/helm/pull/2656.diff
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> Alexander Karbivnichiy ***@***.***> writes:
>
>> 1.  ( ) text/plain          (*) text/html           
>>
>> C-h f, describe-function in Helm throws an error on candidates with long symbol class prefixes, like "c-v'*-" (6 chars).
>>
>> How to reproduce:
>> C-h f
>> input "yas/minor-mode"
>> helm-completion-style custom variable must be defailt, 'helm.
>>
>> What causes the error:
>> yas/minor-mode symbol class shown as prefix is "c-v'*-" :
>
> From which package yas/minor-mode is coming?
> I tried installing yasnippet package and it doesn't provide such symbol,
> it provide yas-minor-mode with "c" as prefix.
> Maybe your yasnippet package is not up to date?

Seems "yas/" prefixed symbols have been changed to "yas-" 11 years ago,
so yes probably you are not up to date ;-)

https://github.com/joaotavora/yasnippet/commit/bc4cfbbb045d683e8f509f21b38b8ed3231709ca

>> 
>> " c " command " - " obsolete, 'byte-obsolete-info " v " var, not a
>> defcustom " ' " local-variable-if-set-p " * " not default value if
>> buffer local " - " 'byte-obsolete-variable
>>
>> help--symbol-class currently can return at most 8 characters long symbol class.
>> This line in helm-symbol-completion-table-affixation causes the error:
>>
>> (propertize
>>     " " 'display (concat it (make-string (- 5 (length it)) ? )))
>>
>> make-string here gets negative number argument on candidates with long symbol classes.
>>
>> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>>
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/emacs-helm/helm/pull/2656
>>
>> Commit Summary
>>
>>   • e70dbcb 'helm-symbol-completion-table-affixation', fix 'make-string' error
>>
>> File Changes
>>
>> (1 file)
>>
>>   • M helm-mode.el (29)
>>
>> Patch Links:
>>
>>   • https://github.com/emacs-helm/helm/pull/2656.patch
>>   • https://github.com/emacs-helm/helm/pull/2656.diff
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> From which package yas/minor-mode is coming? I tried installing yasnippet package and it doesn't provide such symbol,

The latest "yasnippet" package from melpa. 20240308.815
I'm trying to find where that alias comes from.

**Comment by karbiv** [comment]
It's yasnippet.el, line 5242, dynamic symbol definition:

```
(when yas-alias-to-yas/prefix-p
  (dolist (sym yas--backported-syms)
    (let ((backported (intern (replace-regexp-in-string "\\`yas-" "yas/" (symbol-name sym)))))
      (when (boundp sym)
        (make-obsolete-variable backported sym "yasnippet 0.8")
        (defvaralias backported sym))
      (when (fboundp sym)
        (make-obsolete backported sym "yasnippet 0.8")
        (defalias backported sym))))
  (make-obsolete 'yas/root-directory 'yas-snippet-dirs "yasnippet 0.8")
  (defvaralias 'yas/root-directory 'yas-snippet-dirs))
```

This chunk: **(intern (replace-regexp-in-string "\\`yas-" "yas/" (symbol-name sym)))**

And this bug is for any symbol that has symbol class with more than 5 characters.
`help--symbol-class` Emacs' function can hypothetically return up to 8 characters for a symbol.

**Comment by karbiv** [comment]
I was checking history of that `make-string` line in `helm-symbol-completion-table-affixation`.

`(make-string (- 5 (length it)) ? )`

Half a year ago it was modified to 5 from 4. For some reason.

**Comment by karbiv** [comment]
Other approach to this bug would be not to use `help--symbol-class`, but to create `helm-symbol-class` that returns similar but well defined symbol description characters of `fboundp`, `commandp`, `facep`, etc.

`help--symbol-class` is not properly documented in Emacs or at all.
To understand what does this mean: "**c-v'*-**", I had to read function's code. Single quote means that it can be buffer local. Dashes are unreadable.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> Other approach to this bug would be not to use help--symbol-class, but
> to create helm-symbol-class that returns similar but well defined
> symbol description characters of fboundp, commandp, facep, etc.

Do you want to modify your patch like this or shall I merge it as it is?

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ok, I have now the "yas/" prefixed symbols, and have no errors:

Capture d’écran_2024-03-27_14-40-27

**Comment by thierryvolpiatto** [comment]
Whay about using `(format "%-6s" it)`?
I added a comment about spaces inheriting properties of prefix, this was in emacs -nw  (28) but I can't reproduce on emacs-29, so I guess we can use this (6 seems to fit most cases and anyway we are sure to not have your error, at least we will have a candidate misaligned.) WDYT?
I propose this because with your patch, candidates are not aligned properly, at least with "yas minor" as pattern.

**Comment by karbiv** [comment]
> Ok, I have now the "yas/" prefixed symbols, and have no errors:

Strange.
When `debug-on-error` is nil it should be at least "_Error running timer: (wrong-type-argument wholenump -1) [7 times]_" in *Messages* and buffer doesn't update after typing only "y".

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

>     Ok, I have now the "yas/" prefixed symbols, and have no errors:
>    
> Strange.  When debug-on-error is nil it should be at least "Error
> running timer: (wrong-type-argument wholenump -1) [7 times]" in
> Messages and buffer doesn't update after typing only "y".

I guess it is because the prefix has one char less than you (*), don't
know why though.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> I guess it is because the prefix has one char less than you (*), don't know why though.

That (*) appears if you enable `yas-global-mode`.

**Comment by karbiv** [comment]
You also don't have two (-) on your screenshot, for `'byte-obsolete-info` and `'byte-obsolete-variable`.

Help buffer for `yas/minor-mode` contains this paragraph:
 "_This function is obsolete since yasnippet 0.8; use ‘yas-minor-mode’ instead._"

**Comment by karbiv** [comment]
Ok, so there are a lot of comment that could derail train of thought.
**Summary.**

On my standard setup with all latest packages one symbol called `yas/minor-mode` in Emacs is assigned a lot of properties that result in this symbol class returned by Emacs' `help--symbol-class` in Helm completion buffer:

**c-v'*-**

6 characters in total. And Helm throws error because it expects that `help--symbol-class` never returns anything longer than 5 characters.
Helm can be updated to expect 6 characters, but in this case prefixes in Helm buffers will always consume a lot of line's space.

This PR makes Helm expect at most 4 chars from `help--symbol-class` by new local var `prefix-span`.
90%(or more) of the symbols usually have only 1-2 characters. But this PR doesn't throw error on long chracter occurrences and shifts that symbol's name in Helm buffer preserving alignment of a doc string.

**Comment by karbiv** [comment]
I currently use 2 vertical buffers layout with `helm-split-window-default-side 'same`.
The line space ergonomics look more important in this case.
But I agree that with Helm buffer below in full frame's width the solution with `(format "%-6s" it)` is appealing.

In bigger picture, this bug was detected while researching how Helm could do affixation(column alignment) for current set of completions only, not for the whole set of all symbols in Emacs obarray where longest names always push docstrings to the right and most of them break to the next line when not truncated.

**Comment by karbiv** [comment]
> I propose this because with your patch, candidates are not aligned properly, at least with "yas minor" as pattern.

If this is must be avoided in 100% cases than `prefix-span` binding in PR can be set to 5.
When it's 4 it looks like this:

Screenshot from 2024-03-28 00-33-16

**Comment by thierryvolpiatto** [comment]
Emacs vanilla use `format "%-4s"`, I think we can use the same, the extras "*" can be avoided if `help--symbol-class` is called from the current-buffer (they appear when yas-minor-mode is enabled), here a possible patch, let me know how it look on your screen:

```elisp
diff --git a/helm-mode.el b/helm-mode.el
index b5792af1..2ed10f00 100644
--- a/helm-mode.el
+++ b/helm-mode.el
@@ -1186,7 +1186,7 @@ is used."
                   (helm-make-separator comp max-len)))
            (doc (ignore-errors
                   (helm-get-first-line-documentation sym)))
-           (symbol-class (help--symbol-class sym))
+           (symbol-class (with-helm-current-buffer (help--symbol-class sym)))
            (group (helm-group-p sym))
            (key (helm-completion-get-key sym)))
       (list
@@ -1197,7 +1197,15 @@ is used."
          ;; Not already defined function. To test add an advice on a non
          ;; existing function.
          (propertize comp 'face 'helm-completion-invalid))
-       ;; Prefix.
+       ;; Prefixes.
+       ;; " c " command
+       ;; " - " obsolete, 'byte-obsolete-info
+       ;; " v " var, not a defcustom
+       ;; " ' " local-variable-if-set-p
+       ;; " * " not default value if buffer local
+       ;; " - " 'byte-obsolete-variable
+       ;; help--symbol-class currently can return at most 8 characters long
+       ;; symbol class.
        (helm-aand (cond ((and symbol-class group)
                          (concat "g" symbol-class))
                         ((and (not (string= symbol-class ""))
@@ -1206,8 +1214,9 @@ is used."
                         (t "i"))
                   (propertize it 'face 'helm-completions-detailed)
                   (propertize
-                   ;; (format "%-4s" it) makes spaces inheriting text props.
-                   " " 'display (concat it (make-string (- 5 (length it)) ? ))))
+                   ;; (format "%-4s" it) may make spaces inheriting text props
+                   ;; with emacs -nw in emacs<29.
+                   " " 'display (format "%-4s" it)))
        ;; Suffix.
        (if doc
            (helm-aand (propertize doc 'face 'helm-completions-detailed)

```

**Comment by karbiv** [comment]
> let me know how it look on your screen

Screenshot from 2024-03-28 08-41-29

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

>     let me know how it look on your screen
>    
> Screenshot.from.2024-03-28.08-41-29.png (view on web)

Ok, looks good to me, is it acceptable for you? if so I will apply this
simple patch (using format 4s).

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> Ok, looks good to me, is it acceptable for you? if so I will apply this simple patch (using format 4s).

It fixes the bug caused by `make-string` completely.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     Ok, looks good to me, is it acceptable for you? if so I will apply this simple patch (using format 4s).
>    
> It fixes the bug caused by make-string completely.

Ok merged.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Pull request closed without merging**
