### PR TITLE
Change embedded TABs to \t\t in help messages

### PR DESCRIPTION
**Pull request by hmelman**

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Ok, thanks merged, I have resolved the conflicts, please don't forget to merge
your branch with master next time.

**Comment by hmelman** [comment]
Sorry, I couldn't quite figure out what was wrong this time.

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> Sorry, I couldn't quite figure out what was wrong this time.

Always pull before doing any changes ;-)

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hmelman** [comment]
I did. At least I think I did :)

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> I did. At least I think I did :)

I didn't explain well, sorry.
The point is to update your helm clone with the official helm repo.

The command to use is git-fetch. (or git fetch).

But you need to have the upstream repo configured, for this you have to
run:

git-remote add upstream https://github.com/emacs-helm/helm.git

Then you can run: 

git-fetch upstream

and finally you have to merge:

git-merge HEAD origin/upstream

Now you are up to date with helm main repo.

NOTE: You have better time using magit to do all this.
 
-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hmelman** [comment]
Yup, found all that, I have a little script of instructions in an org doc. I know I ran such things but I was probably in the wrong checked out branch or something.  I have a master, origin and upstream as expected and I did the work in a helm-help branch. Does it matter what branch "I'm in" and if so which should it be?

And yes, I have started to use Magit, but that's another learning curve as well. :)

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> Yup, found all that, I have a little script of instructions in an org
> doc. I know I ran such things but I was probably in the wrong checked
> out branch or something. I have a master, origin and upstream as
> expected and I did the work in a helm-help branch.

It seemed you had two branches (other than master).

> Does it matter what branch "I'm in" and if so which should it be?

You have first to sync your master with upstream master, then switch to
your working branch and merge with your master (local).

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Or alternatively, rebase your working branch onto the new HEAD of master (that sounds more frightening as it is).  I like that method because it results in a linear history afterwards.  The possibly needed conflict solving work to do is the same for the two methods.

**Pull request merged**
