### PR TITLE
Add documentation to hook variables.

### PR DESCRIPTION
**Pull request by xiongtx**
Address #1386 by adding documentation to `helm-exit-minibuffer-hook` and
`helm-cleanup-hook`.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks, more generally don't modify indentation, trailing white spaces etc... in same commit, it make hard the read of the diff.

Thanks.

**Comment by xiongtx** [comment]
OK, but I have `whitespace-cleanup` in my `before-save-hook` to get rid of excess whitespace in my files before they are committed. 

This seems like a good idea in general. Is it something we can adopt as a standard for the project?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> OK, but I have whitespace-cleanup in my before-save-hook to get rid of
> excess whitespace in my files before they are committed.
>
> This seems like a good idea in general. Is it something we can adopt
> as a standard for the project?

No thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
*Mea culpa*.

By the way, you can see the [diff with whitespace ignored](https://github.com/blog/967-github-secrets) by appending a `?w=1` do the url.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> By the way, you can see the diff with whitespace ignored by appending a ?w=1 do the url.

Good to know, thanks.

-- 
Thierry

**Pull request merged**
