### PR TITLE
make helm-M-x-class's filtered-candidate-transformer customizable

### PR DESCRIPTION
**Pull request by zbelial**
It seems `filtered-candidate-transformer` should be a function, as it's used in `(apply f ..)` form. So I use a lambda.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
太阳 ***@***.***> writes:

> It seems filtered-candidate-transformer should be a function, as it's used in (apply f ..) form. So I use a lambda.

No, this will not work.
When fuzzy-matching is used helm-source.el adds the fuzzy sort fn on top
and candidates are finally sorted, so I would use a boolean instead to
control whether we are sorting or not (it is a defvar here, just make it
a defcustom):

diff --git a/helm-command.el b/helm-command.el
index bf7c4e1c..23189fae 100644
--- a/helm-command.el
+++ b/helm-command.el
@@ -255,6 +255,7 @@ algorithm."
   (remove-hook 'helm-move-selection-after-hook
                #'helm-M-x--move-selection-after-hook))
 
+(defvar helm-M-x-history-transformer-nosort t)
 (defclass helm-M-x-class (helm-source-in-buffer helm-type-command)
   ((requires-pattern :initform 0)
    (must-match :initform t)
@@ -287,9 +288,11 @@ Arg HISTORY default to `extended-command-history'."
   (setq helm--mode-line-display-prefarg t)
   (let* ((pred (or predicate #'commandp))
          (helm-fuzzy-sort-fn (lambda (candidates _source)
-                               ;; Sort on real candidate otherwise
-                               ;; "symbol (<binding>)" is used when sorting.
-                               (helm-fuzzy-matching-default-sort-fn-1 candidates t)))
+                               (if helm-M-x-history-transformer-nosort
+                                   candidates
+                                 ;; Sort on real candidate otherwise
+                                 ;; "symbol (<binding>)" is used when sorting.
+                                 (helm-fuzzy-matching-default-sort-fn-1 candidates t))))
          (sources `(,(helm-make-source "Emacs Commands history" 'helm-M-x-class
                        :data (lambda ()
                                (helm-comp-read-get-candidates
@@ -301,6 +304,10 @@ Arg HISTORY default to `extended-command-history'."
                                 ;; Ensure using empty string to
                                 ;; not defeat helm matching fns [1]
                                 pred nil nil ""))
+                       :filtered-candidate-transformer
+                       (if helm-M-x-history-transformer-nosort
+                           #'helm-M-x-transformer-no-sort
+                         #'helm-M-x-transformer)
                        :fuzzy-match helm-M-x-fuzzy-match)
                     ,(helm-make-source "Emacs Commands" 'helm-M-x-class
                        :data (lambda ()

> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/emacs-helm/helm/pull/2679
>
> Commit Summary
>
>   • 857d391 make helm-M-x-class's filtered-candidate-transformer customizable
>
> File Changes
>
> (1 file)
>
>   • M helm-command.el (8)
>
> Patch Links:
>
>   • https://github.com/emacs-helm/helm/pull/2679.patch
>   • https://github.com/emacs-helm/helm/pull/2679.diff
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by zbelial** [comment]
Thanks. Sorry I didn't understand it well, I'll read code related and modify my PR according to your advice.

**Comment by thierryvolpiatto** [comment]
Merged! thanks.

PS: Please always rebase on master before commiting new stuff.

**Comment by zbelial** [comment]
> PS: Please always rebase on master before commiting new stuff.

Got it. 

Should I close this PR and #2678 ?

**Comment by thierryvolpiatto** [comment]
太阳 ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     PS: Please always rebase on master before commiting new stuff.
>    
> Got it.
>
> Should I close this PR and #2678 ?

Yes, please.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Pull request closed without merging**
