### PR TITLE
 Allow migemo+regex in helm-buffers--match-from-inside (#1175).

### PR DESCRIPTION
**Pull request by momomo5717**
Hi,

I'd like to use `@` form in `helm-mini`.
Could `helm-mm-migemo-forward` be used in `helm-buffers--match-from-inside`?

And it seems `helm-mm-migemo-forward` could be better to allow regex in `helm-moccur-action` (#1185).

BTW, should I separate the PR?

Thank you.

P.S. It seems the following declarations could be needed to suppress warnings in helm-regexp and helm-multi-match.

For helm-regexp
```emacs-lisp
(declare-function helm-grep-split-line "helm-grep")
(declare-function helm-grep-highlight-match "helm-grep")
(declare-function helm-buffer-list "helm-buffers")
(declare-function helm-comp-read "helm-mode")
```

For helm-multi-match
```emacs-lisp
(declare-function helm-buffer-get "helm")
```

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> P.S. It seems the following declarations could be needed to suppress warnings in helm-regexp and helm-multi-match.
>
> For helm-regexp
>
> (declare-function helm-grep-split-line "helm-grep")
> (declare-function helm-grep-highlight-match "helm-grep")
> (declare-function helm-buffer-list "helm-buffers")
> (declare-function helm-comp-read "helm-mode")
>
> For helm-multi-match
>
> (declare-function helm-buffer-get "helm")

I can't reproduce these warnings, do they appear when you compile with
make ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by momomo5717** [comment]
>I can't reproduce these warnings, do they appear when you compile with make ?

When I use `auto-async-byte-compile` on the buffer, the warnings occurs.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

>     I can't reproduce these warnings, do they appear when you compile with make ?
>    
> When I use auto-async-byte-compile on the buffer, the warnings occurs.

Yes, that's normal, if you use make or if you async-compile the whole
helm directory it should not happen.
(Should not happen when compiled from package.el).

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by momomo5717** [comment]
Thank you for the reply.

>Yes, that's normal, if you use make or if you async-compile the whole
>helm directory it should not happen.
>(Should not happen when compiled from package.el).

Sorry for my lack of knowledge about that.

Thank you for explaining it.

**Pull request merged**
