### PR TITLE
Improve action list in helm-org.el

### PR DESCRIPTION
**Pull request by jagrg**
This PR makes the action list more like org-agenda bulk commands:

- Archive subtree
- Change todo state
- Set tags
- Refile
- Schedule
- Set deadline

Question: In helm-org--open-heading-in-indirect-buffer, is the set-window-prev-buffers function still needed? If I kill the indirect buffer the non-indirect buffer is not killed, so I'm not sure what the issue is.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks merged.

**Comment by thierryvolpiatto** [comment]
>Question: In helm-org--open-heading-in-indirect-buffer, is the set-window-prev-buffers function still >needed? If I kill the indirect buffer the non-indirect buffer is not killed, so I'm not sure what the issue is.

I have no idea, @alphapapa wrote this and have a much better knowledge of org than me, maybe he can answer?

**Comment by thierryvolpiatto** [comment]
Apparently you are using an org version not compatible with Emacs-26 and even Emacs-27!

```
In helm-org-set-tags:
helm-org.el:277:55:Warning: org-get-tags called with 2 arguments, but accepts
    only 0
helm-org.el:276:68:Warning: org-get-tags called with 2 arguments, but accepts
    only 0
```
Probably use something like this:

``` elisp
(defun helm-org-get-tags (&rest args)
  (condition-case _err
      (apply 'org-get-tags args)
    (wrong-number-of-arguments (org-get-tags))))
```

**Comment by jagrg** [comment]
Thanks. I removed the args in https://github.com/emacs-helm/helm/pull/2167. I don't think they are needed.

**Comment by alphapapa** [comment]
Hi,

A few issues/concerns here:

* > Apparently you are using an org version not compatible with Emacs-26 and even Emacs-27!

@jagrg What Emacs and Org versions are you using to develop this PR?  It would be good to know this so we can all at least be aware of potential differences.

* In https://github.com/emacs-helm/helm/pull/2166/commits/2c00c5c9cb964e0243096aa07679c3e9dadfb1cb you removed the call to `org-show-context`.  Why?  It was there for a reason.
* In that commit, you also removed the sharp-quote [here](https://github.com/emacs-helm/helm/pull/2166/commits/2c00c5c9cb964e0243096aa07679c3e9dadfb1cb#diff-9f0a5b5ad44f090ce3e8fe6a47d17f13R316).  Why?  It was there for a reason.
* `helm-org-execute` should probably be a wrapper around `org-with-point-at` and have a more descriptive name, like `helm-org-with-point-at`.
* In https://github.com/emacs-helm/helm/pull/2166/commits/1562e58d79cea45c4b2e1d9f3572937c2dea5696, rather than write your own tag completion code, can you use the existing `helm-org-completing-read-tags`?
* In that commit, it seems inconsistent and confusing for the "Add Tags" action to *replace all existing tags* and the "Remove Tags" action to only remove certain tags.
* In https://github.com/emacs-helm/helm/pull/2166/commits/86fd967f64c4565c20b43f40646c2708e6e0e772, you should use `org-store-link` rather than building the link manually.  That way you will also respect the user's setting in `org-id-link-to-org-use-id`.  It will also simplify that function.
* In fact, it would probably be better to replace that action altogether with "Store link to heading", which the user can then insert anywhere with the standard Org key binding `C-c C-l`.  All the command would need to do then is:
```el
(org-with-point-at marker
  (org-store-link))
```
* In https://github.com/emacs-helm/helm/pull/2166/commits/da41fccc1fbea1843b897941be4a8f5755331900 you seem to have completely changed the purpose of the command and thrown away all the work put into it.  I spent significant time rewriting and testing that command to behave in specific ways after discussing it at length with @thierryvolpiatto.  Please revert that change.  If you want to make changes to that command, we should discuss them carefully.

  Please do not make significant changes like that without first understanding the existing code and discussing it.  It is frustrating to have work thrown away carelessly.
* In https://github.com/emacs-helm/helm/pull/2166/commits/b49e31aa34dc5251f49eb5b253d7af858d9a4a46 and https://github.com/emacs-helm/helm/pull/2166/commits/71a0998ce499c6ead07af7d2578df2bbb99979e1, the docstrings should be simpler and more descriptive, e.g.
```
(Schedule|set the deadline of) entry at MARKER.
With prefix, (unschedule|remove deadline).
```

**Comment by alphapapa** [comment]
@thierryvolpiatto Please feel free to tag me in Org-related PRs so I can review them.  I'm glad to have more help with `helm-org.el`, but users who aren't familiar with Org's inner workings sometimes make undesirable changes, and I prefer to avoid regressions.  ;)

**Comment by thierryvolpiatto** [comment]
@jagrg @alphapapa , let me know if something needs to be reverted.

**Comment by jagrg** [comment]
On 04 Jul 2019, alphapapa <notifications@github.com> wrote:

> A few issues/concerns here:
>
> @jagrg What Emacs and Org versions are you using to develop this PR?  It would be good to know this so we can all at least be aware of potential differences.

@alphapapa I understand your frustration. Maybe Thierry was a bit too quick here. Anyhow, I'm using Emacs version 26.2 and Org version 9.2.4.

>
> * In https://github.com/emacs-helm/helm/pull/2166/commits/2c00c5c9cb964e0243096aa07679c3e9dadfb1cb you removed the call to `org-show-context`.  Why?  It was there for a reason.

It's still there, under the helm-org-execute macro.

> * In that commit, you also removed the sharp-quote [here](https://github.com/emacs-helm/helm/pull/2166/commits/2c00c5c9cb964e0243096aa07679c3e9dadfb1cb#diff-9f0a5b5ad44f090ce3e8fe6a47d17f13R316).  Why?  It was there for a reason.

Can you explain the reason.

> * `helm-org-execute` should probably be a wrapper around `org-with-point-at` and have a more descriptive name, like `helm-org-with-point-at`.

Sure. Do you want to do that?

> * In https://github.com/emacs-helm/helm/pull/2166/commits/1562e58d79cea45c4b2e1d9f3572937c2dea5696, rather than write your own tag completion code, can you use the existing `helm-org-completing-read-tags`?

I prefer my implementation, which requires less typing in the minibuffer.

> * In that commit, it seems inconsistent and confusing for the "Add Tags" action to *replace all existing tags* and the "Remove Tags" action to only remove certain tags.

Makes sense. When I read "Add Tags" I understand that tags are going to be added (not removed). When I read "Remove Tags", and there's a list of local tags displayed, I understand that any tags selected or marked will be removed, in which case the "Add Tags" source should be changed. I'll give this another thought.

> * In https://github.com/emacs-helm/helm/pull/2166/commits/86fd967f64c4565c20b43f40646c2708e6e0e772, you should use `org-store-link` rather than building the link manually.  That way you will also respect the user's setting in `org-id-link-to-org-use-id`.  It will also simplify that function.

I agree.

> * In fact, it would probably be better to replace that action altogether with "Store link to heading", which the user can then insert anywhere with the standard Org key binding `C-c C-l`.  All the command would need to do then is:
> ```el
> (org-with-point-at marker
>   (org-store-link))
> ```

Sure. Do you want to do that?

> * In https://github.com/emacs-helm/helm/pull/2166/commits/da41fccc1fbea1843b897941be4a8f5755331900 you seem to have completely changed the purpose of the command and thrown away all the work put into it.  I spent significant time rewriting and testing that command to behave in specific ways after discussing it at length with @thierryvolpiatto.  Please revert that change.  If you want to make changes to that command, we should discuss them carefully.
>
>   Please do not make significant changes like that without first understanding the existing code and discussing it.  It is frustrating to have work thrown away carelessly.

Again, I understand your frustration, but I'm still not sure I agree with your implementation, which ignores org-refile-targets and creates a new refiling mechanism. I would vote to stick with the way Org works for refiling entries.

> * In https://github.com/emacs-helm/helm/pull/2166/commits/b49e31aa34dc5251f49eb5b253d7af858d9a4a46 and https://github.com/emacs-helm/helm/pull/2166/commits/71a0998ce499c6ead07af7d2578df2bbb99979e1, the docstrings should be simpler and more descriptive, e.g.
> ```
> (Schedule|set the deadline of) entry at MARKER.
> With prefix, (unschedule|remove deadline).
> ```

Sure.

**Comment by jagrg** [comment]
On 04 Jul 2019, alphapapa <notifications@github.com> wrote:

> @thierryvolpiatto Please feel free to tag me in Org-related PRs so I can review them.  I'm glad to have more help with `helm-org.el`, but users who aren't familiar with Org's inner workings sometimes make undesirable changes, and I prefer to avoid regressions.  ;)

@thierryvolpiatto You can also tag me in Org-related PRs so I can review them. I'm glad to have more help with helm-org.el.

@alphapapa thanks for your review. I'll cc you next time.

**Comment by alphapapa** [comment]
@thierryvolpiatto 

> let me know if something needs to be reverted.

Please revert https://github.com/emacs-helm/helm/commit/da41fccc1fbea1843b897941be4a8f5755331900.  As I explained, that commit changes not merely how the command works, but what it does.  It throws away half of the command's functionality.  We should carefully discuss making changes like that before making them.

**Comment by alphapapa** [comment]
@jagrg 

> I'm using Emacs version 26.2 and Org version 9.2.4.

Okay, that should be fine.  However, Org has been making some backwards-incompatible changes recently, e.g. in function signatures and removing functions, so we should keep those in mind when writing related code, because some Org users don't upgrade it frequently.  We don't want to break compatibility unnecessarily.

>> * In [2c00c5c](https://github.com/emacs-helm/helm/pull/2166/commits/2c00c5c9cb964e0243096aa07679c3e9dadfb1cb) you removed the call to `org-show-context`. Why? It was there for a reason.

> It's still there, under the helm-org-execute macro.

Okay, that's good.  However, as I said, we should wrap `org-with-point-at` instead.

> >  * In that commit, you also removed the sharp-quote [here](2c00c5c#diff-9f0a5b5ad44f090ce3e8fe6a47d17f13R316).  Why?  It was there for a reason.

> Can you explain the reason.

Search for e.g. `emacs sharp quote` and you'll find excellent explanations.

This is a kind of change you should not make: you did not understand the purpose of the code, so you deleted it.  If you don't understand a piece of code, leave it be.  

And while you did a good job splitting up the PR into relatively atomic commits, this change was unnecessary and unrelated to the commit's purpose.

> >  * `helm-org-execute` should probably be a wrapper around `org-with-point-at` and have a more descriptive name, like `helm-org-with-point-at`.

> Sure. Do you want to do that?

No thanks.  It's your PR, so I'll let you make the necessary changes.

>>  * In 1562e58, rather than write your own tag completion code, can you use the existing `helm-org-completing-read-tags`?

> I prefer my implementation, which requires less typing in the minibuffer.

Rather than have multiple, slightly different implementations, we should reuse and improve existing ones.  If your implementation is better, rather than adding a new function, you should improve the existing one so everything benefits.

Having said that, please explain the difference between them and how yours is better.  If yours is better, and compatible with the uses of the other one, let's replace the old one with yours.  Let's try to reuse and improve code as much as possible.

> >  * In that commit, it seems inconsistent and confusing for the "Add Tags" action to *replace all existing tags* and the "Remove Tags" action to only remove certain tags.

> Makes sense. When I read "Add Tags" I understand that tags are going to be added (not removed). When I read "Remove Tags", and there's a list of local tags displayed, I understand that any tags selected or marked will be removed, in which case the "Add Tags" source should be changed. I'll give this another thought.

Okay.  Maybe you should rename that source to "Set tags" and add another "Add tags" action.

> > * In 86fd967, you should use `org-store-link` rather than building the link manually.  That way you will also respect the user's setting in `org-id-link-to-org-use-id`.  It will also simplify that function.

> I agree.

> > * In fact, it would probably be better to replace that action altogether with "Store link to heading", which the user can then insert anywhere with the standard Org key binding `C-c C-l`.  All the command would need to do then is:
 ```el
 (org-with-point-at marker
   (org-store-link))
 ```

> Sure. Do you want to do that?

No thanks, since it's your PR, I'll let you make the necessary changes.

> >  * In da41fcc you seem to have completely changed the purpose of the command and thrown away all the work put into it.  I spent significant time rewriting and testing that command to behave in specific ways after discussing it at length with @thierryvolpiatto.  Please revert that change.  If you want to make changes to that command, we should discuss them carefully.

> >   Please do not make significant changes like that without first understanding the existing code and discussing it.  It is frustrating to have work thrown away carelessly.

> Again, I understand your frustration, but I'm still not sure I agree with your implementation, which ignores org-refile-targets and creates a new refiling mechanism. I would vote to stick with the way Org works for refiling entries.

You don't seem to understand: you replaced the command with one that does not do the same thing.  You didn't merely change how the command works, you changed what it does.  You threw away half of the command's functionality.  The implementation was carefully discussed almost 2 years ago in https://github.com/emacs-helm/helm/pull/1829, which you could have found by looking in the `blame` for that code and linking to that PR from the commit message.

It's not okay to throw away code because you don't understand it, or don't personally use it, or don't prefer its implementation.  Thousands of people use Helm every day, and many hours of work have been put into it.  Additions and fixes are fine; major changes and discarding of functionality should be discussed first.

**Comment by thierryvolpiatto** [comment]
@alphapapa and @jagrg I have reverted all recent changes in helm-org.el.
Please make PR's from there trying to keep in agreement each other.

Thanks.


alphapapa <notifications@github.com> writes:

> @jagrg
>
>     I'm using Emacs version 26.2 and Org version 9.2.4.
>    
> Okay, that should be fine. However, Org has been making some backwards-incompatible changes recently, e.g. in function signatures and removing functions, so we should
> keep those in mind when writing related code, because some Org users don't upgrade it frequently. We don't want to break compatibility unnecessarily.
>
>           o In 2c00c5c you removed the call to org-show-context. Why? It was there for a reason.
>    
>     It's still there, under the helm-org-execute macro.
>    
> Okay, that's good. However, as I said, we should wrap org-with-point-at instead.
>
>           o In that commit, you also removed the sharp-quote here. Why? It was there for a reason.
>    
>     Can you explain the reason.
>    
> Search for e.g. emacs sharp quote and you'll find excellent explanations.
>
> This is a kind of change you should not make: you did not understand the purpose of the code, so you deleted it. If you don't understand a piece of code, leave it be.
>
> And while you did a good job splitting up the PR into relatively atomic commits, this change was unnecessary and unrelated to the commit's purpose.
>
>           o helm-org-execute should probably be a wrapper around org-with-point-at and have a more descriptive name, like helm-org-with-point-at.
>    
>     Sure. Do you want to do that?
>    
> No thanks. It's your PR, so I'll let you make the necessary changes.
>
>           o In 1562e58, rather than write your own tag completion code, can you use the existing helm-org-completing-read-tags?
>    
>     I prefer my implementation, which requires less typing in the minibuffer.
>    
> Rather than have multiple, slightly different implementations, we should reuse and improve existing ones. If your implementation is better, rather than adding a new
> function, you should improve the existing one so everything benefits.
>
> Having said that, please explain the difference between them and how yours is better. If yours is better, and compatible with the uses of the other one, let's replace
> the old one with yours. Let's try to reuse and improve code as much as possible.
>
>           o In that commit, it seems inconsistent and confusing for the "Add Tags" action to replace all existing tags and the "Remove Tags" action to only remove
>             certain tags.
>    
>     Makes sense. When I read "Add Tags" I understand that tags are going to be added (not removed). When I read "Remove Tags", and there's a list of local tags
>     displayed, I understand that any tags selected or marked will be removed, in which case the "Add Tags" source should be changed. I'll give this another thought.
>    
> Okay. Maybe you should rename that source to "Set tags" and add another "Add tags" action.
>
>           o In 86fd967, you should use org-store-link rather than building the link manually. That way you will also respect the user's setting in
>             org-id-link-to-org-use-id. It will also simplify that function.
>    
>     I agree.
>    
>           o In fact, it would probably be better to replace that action altogether with "Store link to heading", which the user can then insert anywhere with the
>             standard Org key binding C-c C-l. All the command would need to do then is:
>    
> (org-with-point-at marker
>   (org-store-link))
>
>     Sure. Do you want to do that?
>    
> No thanks, since it's your PR, I'll let you make the necessary changes.
>
>           o In da41fcc you seem to have completely changed the purpose of the command and thrown away all the work put into it. I spent significant time rewriting and
>             testing that command to behave in specific ways after discussing it at length with @thierryvolpiatto. Please revert that change. If you want to make
>             changes to that command, we should discuss them carefully.
>    
>         Please do not make significant changes like that without first understanding the existing code and discussing it. It is frustrating to have work thrown away
>         carelessly.
>        
>     Again, I understand your frustration, but I'm still not sure I agree with your implementation, which ignores org-refile-targets and creates a new refiling
>     mechanism. I would vote to stick with the way Org works for refiling entries.
>    
> You don't seem to understand: you replaced the command with one that does not do the same thing. You didn't merely change how the command works, you changed what it
> does. You threw away half of the command's functionality. The implementation was carefully discussed almost 2 years ago in #1829, which you could have found by
> looking in the blame for that code and linking to that PR from the commit message.
>
> It's not okay to throw away code because you don't understand it, or don't personally use it, or don't prefer its implementation. Thousands of people use Helm every
> day, and many hours of work have been put into it. Additions and fixes are fine; major changes and discarding of functionality should be discussed first.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alphapapa** [comment]
Thanks.  I'll be happy to review the commits in these recent PRs if @jagrg wants to post them again, I just ask that the PRs be split up according to purpose.  I'd rather review several, smaller PRs containing related commits, than a couple large ones that do several unrelated things at once.

**Comment by jagrg** [comment]
On 05 Jul 2019, alphapapa <notifications@github.com> wrote:

> Thanks.  I'll be happy to review the commits in these recent PRs if @jagrg wants to post them again, I just ask that the PRs be split up according to purpose.  I'd rather review several, smaller PRs containing related commits, than a couple large ones that do several unrelated things at once.

Sure, I'll resend them again in smaller chunks. I'll see what I can do.

**Comment by alphapapa** [comment]
@jagrg Thanks.  Apologies if I was harsh in my comments.  I do appreciate your work.

**Pull request merged**
