### PR TITLE
helm-locate.el: Add support for Apple MacOS 'mdfind -name' as locate command

### PR DESCRIPTION
**Pull request by rswgnu**
Just look at and apply the helm-locate.el changes (not the other files) to add Spotlight-type searching as the default under MacOS because mdfind is preconfigured with a database and 'locate' is not.  So this enables out-of-the-box locate-type searching under MacOS.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Please create a new branch locally from master and create a PR with only the changes requested for this feature.

**Comment by thierryvolpiatto** [comment]
Also please follow the conventions for commit writing.

Thanks.

**Comment by rswgnu** [comment]
On Wed, Sep 20, 2017 at 1:55 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> Please create a new branch locally from master and create a PR with only
> the changes requested for this feature.
>
​This commit is the only change necessary for this feature.  It is 2
changed lines so you can hand apply it if you can't just apply this commit
alone:
  https://github.com/emacs-helm/helm/pull/1875/commits/e9609af

Bob

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 1:07 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> Closed #1875 <https://github.com/emacs-helm/helm/pull/1875>.
>
​Did you make the change?  mdfind does have some limitations compared to
locate but it works without any additional setup effort, so it would
provide a better initial experience for new users.

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> On Fri, Sep 22, 2017 at 1:07 AM, Thierry Volpiatto <notifications@github.com
>> wrote:
>
>> Closed #1875 <https://github.com/emacs-helm/helm/pull/1875>.
>>
> ​Did you make the change? mdfind does have some limitations compared to
> locate but it works without any additional setup effort, so it would
> provide a better initial experience for new users.

Please just make a new PR against master and I will apply.

PS: To not mix this with your other changes, create locally a new branch
against master, make the mdfind change and push it to your github repo, 
then just create the PR with this branch.

Thanks.

-- 
Thierry

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 9:57 AM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Please just make a new PR against master and I will apply.
>

​Okay, will do.

Bob
​

**Pull request closed without merging**
