### PR TITLE
Incrementally committed global mouse support changes

### PR DESCRIPTION
**Pull request by rswgnu**
Not yet tested and no doubt some issues but has the bulk of the needed infrastructure for global mouse bindings and issues should be fairly easily localizable.

### CODE REVIEW

**Comment by rswgnu** [comment]
I have done initial testing now and the results are good.  I could not trigger any errors even with drag events when using helm-info, helm-occur or helm-find-files.   I have all the global mouse key capability I want.  Switching mouse key modes can be done with standard (setq helm-allow-mouse <value>) where <value> is one of t (local helm mouse bindings), nil (no mouse bindings) or 'global-mouse-bindings (global mouse bindings in helm buffers) or via  the interactive custom-option for helm-allow-mouse.  Changes are immediate once you restart a helm session.

I am sure there will be issues but they should largely be edge cases that can be addressed with localized fixes.  You do need to use global mouse bindings that make sense within helm buffers, i.e. for read-only buffers, so mouse-yank-primary, is not one that you can get any use out of.

**Comment by thierryvolpiatto** [comment]
Now, helm is completely broken, I couldn't debug, helm is quitting immediately with no error when pressing RET or whatever on any candidate.

**Comment by thierryvolpiatto** [comment]
FYI, read this about commit messages:
https://chris.beams.io/posts/git-commit/
To summarize:

The seven rules of a great Git commit message

    Keep in mind: This has all been said before.

    Separate subject from body with a blank line
    Limit the subject line to 50 characters
    Capitalize the subject line
    Do not end the subject line with a period
    Use the imperative mood in the subject line
    Wrap the body at 72 characters
    Use the body to explain what and why vs. how

In addition:
No need to paste the code you have added in the commit message it is already in the diff.
See how other commits are done in helm:

example:

Here are some changes

I am here explaing what are these changes globally.

* helm.el (foo-function): Explain specific changes to this function
no need to paste code added or removed, it is already visible in diff.
* helm-foo.el (bar-function): Explain specific changes to `bar-function'.

**Comment by thierryvolpiatto** [comment]
Also don't modify indentation, even if it is wrong originally, this make diff unreadable, hopefully we can toggle this with `-w` flag.

**Comment by thierryvolpiatto** [comment]
I tried bisecting commit by commit, but it is really hard to debug, very unstable, sometimes error appear, sometime not, but keys are not working, mouse is unable to select candidate (mouse-1) and send error on mouse-2 (even before the commit that add mouse-set-point), stopping for now, I will try to continue debugging this later.

**Comment by xiongtx** [comment]
> Also don't modify indentation, even if it is wrong originally, this make diff unreadable

Add `?w=1` to the end of the GitHub URL to hide whitespace differences.

More generally, these whitespace issues wouldn't occur if Helm files were properly `whitspace-cleanup`ed. Adding `whitespace-cleanup` to `before-save-hook` takes care of this automatically.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

>     Also don't modify indentation, even if it is wrong originally, this make diff unreadable
>
> Add ?w=1 to the end of the GitHub URL to hide whitespace differences.

Thanks, I use generally "-w" for this in magit.

> More generally, these whitespace issues wouldn't occur if Helm files
> were properly whitspace-cleanuped.

It is a problem of indentation which behave differently across emacs versions.

> Adding whitespace-cleanup to before-save-hook takes care of this
> automatically.

I already explained to you that this is not a good thing to do.


--
Thierry

**Comment by rswgnu** [comment]
On Sat, Sep 16, 2017 at 1:49 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> Also don't modify indentation, even if it is wrong originally, this make
> diff unreadable, hopefully we can toggle this with -w flag.
>
​Those were an unintended result of a package I was trying; I have now
disabled it for the future so this won't occur.

Bob

**Comment by rswgnu** [comment]
Thierry wrote:
> Now, helm is completely broken, I couldn't debug, helm is quitting immediately with no error 
> when pressing RET or whatever on any candidate.

I see a few things using helm-info.  Helm properly displays an entry if it generates another helm completion buffer, e.g. try 'calc'.  But if the selection should display another buffer (try 'bovine') then a quit signal is generated instead and this is caught by an unwind-protect by helm so you don't see the error.  The proper info node is selected but the Info buffer is not displayed.  Maybe something is going on with the keymap installation.  It is likely one specific error and the debug log doesn't show anything within the minibuffer handler code where this occurs.

**Comment by rswgnu** [comment]
Global mouse key handling is now working as I need under Helm with the changes under this branch, so you can look at it again.  With one context-sensitive global mouse key bound under the Hyperbole package, I can now do the following in helm buffers and do not require any further changes:

  In an inactive helm buffer, resumes the helm session for that buffer;
  On a candidate line, performs the candidate’s first action and remains in the minibuffer;
  On the first header line, displays a list of actions available for the selected candidate;
  On an action list line, performs the action after exiting the minibuffer;
  At the end of the buffer, quits from helm and exits the minibuffer.
  On a candidate separator line, does nothing.
  In the minibuffer window, ends the helm session and performs the selected item’s action.

My mouse binding also selects the candidate at the point of the click before operating on it (rather than making this two mouse key operations).  A second mouse key shows the actions for the selected candidate without invoking any action.

I do not get any errors that I have seen in my usage but my mouse bindings return point to the minibuffer whenever necesssary.  If you use bindings that do not handle this, helm may give you an error when it tries to return point to a buffer that it has already killed off.  As the helm documentation says, this is the responsibility of the mouse binding developer.  So to test, first use mouse bindings that return point to the minibuffer when active.

**Comment by thierryvolpiatto** [comment]
Here last try:

Debugger entered--Lisp error: (wrong-type-argument window-valid-p #<window 20>)
  window-minibuffer-p(#<window 20>)
  mouse-minibuffer-check((drag-mouse-2 (#<window 20> 398 (68 . 165) 3141119 nil 398 (8 . 9) nil (4 . 12) (8 . 17)) (#<window 3 on helm-files.el> 12681 (68 . 529) 3141316 nil 12681 (8 . 31) nil (4 . 2) (8 . 17))))
  mouse-set-point((drag-mouse-2 (#<window 20> 398 (68 . 165) 3141119 nil 398 (8 . 9) nil (4 . 12) (8 . 17)) (#<window 3 on helm-files.el> 12681 (68 . 529) 3141316 nil 12681 (8 . 31) nil (4 . 2) (8 . 17))))
  mouse-yank-primary((drag-mouse-2 (#<window 20> 398 (68 . 165) 3141119 nil 398 (8 . 9) nil (4 . 12) (8 . 17)) (#<window 3 on helm-files.el> 12681 (68 . 529) 3141316 nil 12681 (8 . 31) nil (4 . 2) (8 . 17))))
  call-interactively(mouse-yank-primary nil nil)
  command-execute(mouse-yank-primary)

**Comment by thierryvolpiatto** [comment]
Also I see there is unrelated commits to this PR...

**Comment by rswgnu** [comment]
As I noted in my prior comment, if you try to use global mouse bindings that are incompatible with helm, you will get errors like this because of the way helm uses with-helm-buffer and the like.  It looks like your yank command is trying to yank into a window that helm has already killed.  This is really an issue buried in helm that is just surfaced by use of incompatible mouse bindings, I believe.  It's not much different than getting a read-only error when trying to edit a read-only buffer.  I would like to eliminate it but it is buried somewhat deeply in helm command processing and so is really an issue for core helm debugging.

So, try to test with mouse bindings that leave the point in the minibuffer or that exit helm and then execute the associated action.  Maybe I'll convert my Hyperbole mouse bindings for standalone use and offer them to you for testing purposes to at least simplify behavioral testing.

**Comment by rswgnu** [comment]
On Tue, Sep 19, 2017 at 3:12 PM, Thierry Volpiatto <notifications@github.com
> wrote:

> Also I see there is unrelated commits to this PR...
>

​Very minimally.  Sometimes small ones creep in during the normal course of
development.

Bob
​

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> On Tue, Sep 19, 2017 at 3:12 PM, Thierry Volpiatto <notifications@github.com
>> wrote:
>
>> Also I see there is unrelated commits to this PR...
>>
>
> ​Very minimally. Sometimes small ones creep in during the normal course of
> development.

No, unless it is really needed I don't want unrelated commits that add
confusion to the already huge PR, i.e it make even more ununderstandable
what you want to achieve.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> As I noted in my prior comment, if you try to use global mouse
> bindings that are incompatible with helm, you will get errors like
> this because of the way helm uses with-helm-buffer and the like. It
> looks like your yank command is trying to yank into a window that helm
> has already killed. This is really an issue buried in helm that is
> just surfaced by use of incompatible mouse bindings, I believe. It's
> not much different than getting a read-only error when trying to edit
> a read-only buffer.  I would like to eliminate it but it is buried
> somewhat deeply in helm command processing and so is really an issue
> for core helm debugging.
>
> So, try to test with mouse bindings that leave the point in the
> minibuffer or that exit helm and then execute the associated
> action. Maybe I'll convert my Hyperbole mouse bindings for standalone
> use and offer them to you for testing purposes to at least simplify
> behavioral testing.

Sorry but I understand nothing at what you are asking, I am just
starting helm with helm-allow-mouse set to t, like all other helm users
using mouse will do, and at the first click (mouse-2) I have an error,
you have to understand that I can't merge such changes in helm for now.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Another one (mouse-3):

Debugger entered--Lisp error: (wrong-type-argument window-valid-p #<window 18>)
  window-minibuffer-p(#<window 18>)
  mouse-minibuffer-check((drag-mouse-3 (#<window 18> 171 (55 . 130) 5704781 nil 171 (6 . 7) nil (7 . 6) (8 . 17)) (#<window 16 on *helm find files*> 366 (55 . 130) 5704835 nil 366 (6 . 7) nil (7 . 11) (8 . 17))))
  mouse-save-then-kill((drag-mouse-3 (#<window 18> 171 (55 . 130) 5704781 nil 171 (6 . 7) nil (7 . 6) (8 . 17)) (#<window 16 on *helm find files*> 366 (55 . 130) 5704835 nil 366 (6 . 7) nil (7 . 11) (8 . 17))))
  call-interactively(mouse-save-then-kill nil nil)
  command-execute(mouse-save-then-kill)
  read-from-minibuffer("Find files or url: " "/home/thierry/labo/github/helm/" (keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #[0 "\306\307\310\311\312\313\305!\314\"\315\316%DC\216\317\302!\210\320\304!\321\211\211\301=\203+

**Comment by rswgnu** [comment]
On Wed, Sep 20, 2017 at 12:35 AM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> Sorry but I understand nothing at what you are asking, I am just
> starting helm with helm-allow-mouse set to t, like all other helm users
> using mouse will do, and at the first click (mouse-2) I have an error,
> you have to understand that I can't merge such changes in helm for now.
>

​I believe this is one isolated problem in the way helm assumes that it can
return to a buffer even though the buffer has been killed by helm prior to
attempting the return.  The global mouse key just exercises the problem.  I
agree that it needs to be fixed and will work on it but would like your
help with it as well if possible since it is within the way helm handles
actions.

And the message you just sent is the same issue, I believe.

Bob

**Comment by thierryvolpiatto** [comment]
Now tried with helm-allow-mouse==global-mouse-bindings, even worst, the minibuffer is lost and the error (mostly the same popup inside the helm-buffer!)

I will try to help on debugging this later, as soon as I have the time.

We have to make also a complete rebase of all commits (see previous posts).

**Comment by rswgnu** [comment]
On Wed, Sep 20, 2017 at 1:12 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> Now tried with helm-allow-mouse==global-mouse-bindings, even worst, the
> minibuffer is lost and the error (mostly the same popup inside the
> helm-buffer!)
>
​I will soon have a setup file with global mouse bindings that do something
in helm modes for you.​


> I will try to help on debugging this later, as soon as I have the time.
>
​Great, thanks.​


> W
> ​​
> e have to mak
> ​​
> e also a complete rebase of all commits (see previous posts).
>
> ​You'll have to helm me with that.  I have not done rebasing though I will
read up on it when I have time.

Bob
​

**Comment by rswgnu** [comment]
I have added rsw-test-global-mouse-bindings.el to let you test with useful global bindings for helm. 
 See the doc in smart-helm and smart-helm-assist for how mouse-2 and mouse-3 should behave, respectively.

**Comment by thierryvolpiatto** [comment]
I tried your branch.
So to summarize:

- With helm-allow-mouse == t
Using `mouse-2` instead of  `down-mouse-2` fixes the different windows error (i.e `down-mouse-2` tries to yank which is wrong)

- With helm-allow-mouse set globally
Does nothing useful in helm-buffer and no more than what we do actually in other buffers.

So from what I can see here, I don't see the need of such changes which are providing the same behavior as the initial commit of global_mouse branch.
At least I can provide the changes of initial commit of global_mouse branch if one want to use the mouse without the bindings for helm, but same, I don't see why one would want the use of the mouse to do nothing in helm buffers.
I understand that you want helm to fit your workflow and started to heavily modifying it for this, but it is not how helm is intended to work i.e starting from buffers generated by itself.
Merging such changes would for sure break helm in many places, so I suggest you try to get use of helm and think at how you could adapt your workflow to it.

Thanks.

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 1:40 AM, Thierry Volpiatto <notifications@github.com>
wrote:
I tried your branch.
So to summarize:

> With helm-allow-mouse == t
> Using mouse-2 instead of down-mouse-2 fixes the different windows error
(i.e down-mouse-2 tries to yank which is wrong)
>
> With helm-allow-mouse set globally
> Does nothing useful in helm-buffer and no more than what we do actually
in other buffers.

​The change let's you program global mouse keys to interoperate with helm.
I provided one
such set of key bindings for [mouse-2] and [mouse-3] for testing. (Though
just FYI, by
default, Hyperbole places those keys on [S-mouse-2] and [S-mouse-3]
(shifted mouse keys
so it doesn't override​ your [mouse-2] and [mouse-3] keys).

​The additional functionality these keys provide is:

  Let's you select a candidate and perform its default action with a single
mouse key
  click; helm requires the user learn two key bindings here, one to select
a candidate
  and another to invoke its action;

  On a candidate line, performs the candidate’s first action and remains in
the
  minibuffer;  I don't believe helm provides a way to      invoke the {C-j}
from the
  mouse; so now, helm completion buffers can be used like menus via the
mouse as needed;

  On the first header line, displays a list of actions available for the
selected
  candidate; helm does nothing with such clicks;

  At the end of the buffer, quits from helm and exits the minibuffer
without performing
  any other action; helm does nothing with such clicks;

  In the minibuffer window, ends the helm session and performs the selected
item’s
  action; helm does nothing with such clicks;
​
  Additionally, though this was not included in the mouse bindings
provided, a mouse
  click on a  source section header will jump to the next (or first)
section of
  candidates ({C-o} binding equivalent).

If you were able to utilize these mouse bindings, I don't see how you can
conclude that
they add nothing to helm buffers beyond what the local mouse bindings do.
Maybe try
again with the pointers above.

> So from what I can see here, I don't see the need of such changes which
are providing the
> same behavior as the initial commit of global_mouse branch.

I'm not sure what you are referring to; this branch was to implement the
global mouse
functionality in a bunch of small commits, so all of those small commits
are needed to
get the desired functionality.

> At least I can provide the changes of initial commit of global_mouse
branch if one want
> to use the mouse without the bindings for helm,

If you mean all of the commits from Sept. 15th, then that would be a great
start.

> but same, I don't see why one would
> want the use of the mouse to do nothing in helm buffers.

Unless you (setq helm-allow-mouse 'global-mouse-bindings) and therefore
know that you
have global bindings set that you want to use in helm sessions, then the
local behavior
of helm mouse control (whether on or off) should be the same as before with
these changes.

> I understand that you want helm to fit your workflow and started to
heavily modifying
> it for this, but it is not how helm is intended to work i.e starting from
buffers
> generated by itself.

The idea of resuming a helm session with a mouse click is but one very
small potential
use of these changes.  If you want to say in practice that is not how a
resume should be
done, okay, but most of the utility is for within helm sessions.

> Merging such changes would for sure break helm in many places, so I
suggest you try to
> get use of helm and think at how you could adapt your workflow to it.

I have been doing this a lot but having the mouse operate in ways I find
helpful is also
beneficial and will help other people who are using both helm and
Hyperbole.  Once these
changes are merged, I am thinking of adding a menu of helm commands to the
top-level
Hyperbole minibuffer menu (fast menu invoked from the keyboard) since I am
already using
that daily internally and finding it helpful for using more of helm.  It
looks like this
(each item is selected by its first letter and help is available for what
each menu item
does).

Helm>  Apropos  Evernote  FindFiles  Grep  HelmMode  InfoIndices  KillRing
Locate  Man  Occur  Regexp  Tags  WorkingFiles

Regards,

Bob

**Comment by rswgnu** [comment]
The recent commits resolve any open issues I found with the Hyperbole context-sensitive mouse bindings.   The rsw-*.el test file binds 3 global mouse keys like so:

mouse-1 keeps its normal global binding but also selects the helm candidate clicked upon

mouse-2 performs the following:
  - At the end of the buffer, quits from helm and exits the minibuffer.
  - On a candidate line, performs the candidate’s first action and remains in the minibuffer;
  - On the top, fixed header line, toggles display of the selected candidate’s possible actions;
  - On an action list line, performs the action after exiting the minibuffer;
  - On a source section header, moves to the next source section or first if on last.
  - On a candidate separator line, does nothing.
  - In the minibuffer window, ends the helm session and performs the selected item’s action.

mouse-3 performs the following:
  - At the end of the buffer, quits from helm and exits the minibuffer.
  - On a candidate line, display’s the candidate’s first action and remains in the minibuffer;
  - On the top, fixed header line, toggles display of the selected candidate’s possible actions;
  - On an action list line, performs the action after exiting the minibuffer;
  - On a source section header, moves to the previous source section or last if on first.
  - On a candidate separator line, does nothing.
  - In the minibuffer window, ends the helm session and performs the selected item’s action.

See if you can test this out and when it works for you we can talk about how the commits must be updated to allow you to merge.

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> The recent commits resolve any open issues I found with the Hyperbole
> context-sensitive mouse bindings.

First try first error, always the same you haven't fixed.

Your commits are still in bad style (you didn't read what I sent about
this apparently).

You are still wanting to heavily modify helm to make it working in a way
I don't accept (i.e starting up from helm buffers), if it was not so
invasive and prone to break helm in an unrecoverable way, I would accept
but here you have to understand I can't accept such changes.

I suggest you make an external package called helm-hyperbole that
provide what you want without breaking helm, I am open to make changes
to helm if needed for your package as long as they don't break current
helm usage.

I will close now this PR, please feel free to come back with reasonable
changes I will be able to merge.

Thanks for your efforts anyway.

--
Thierry

**Comment by rswgnu** [comment]
On Mon, Sep 25, 2017 at 11:42 PM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > The recent commits resolve any open issues I found with the Hyperbole
> > context-sensitive mouse bindings.
>
> First try first error, always the same you haven't fixed.
>

​Let's be clear on what the issue is here so I can look at it.
Do you get an error with my changes when you have helm-allow-mouse set to t
or nil and your global mouse bindings are the standard emacs ones?  If so,
what mouse button do you press and where?  (I have not done any additional
work recently on this scenario).

Do you get an error with ​helm-allow mouse set to 'global-mouse-bindings
and the global bindings file I provided, rsw-*.el?  If so, what mouse
button do you press and where?  (I have been using this scenario and not
seeing any errors).

> ​​
>
> ​​
> Your commits are still in bad style (you didn't read what I sent about
> ​​
>
> ​​
> this apparently).
> ​​
>

​I understand I have not yet applied all of those pointers.  I have focused
more on providing the information needed in the commits rather than the
formatting so far.

> ​​
>
> ​​
>
> ​​
> You are still wanting to heavily modify helm to make it working in a way
> ​​
> I don't accept (i.e starting up from helm buffers),


​That feature is not a change to helm but part of the external Hyperbole
mouse bindings (it just calls helm-resume), so I don't know why ​that would
be an issue.  I don't expect you to merge the mouse bindings; they are just
provided for testing purposes.
​​

> ​​
> if it was not so
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​
> i
> ​​
> ​​
> n
> ​​
> v
> ​​
> a
> ​​
> s
> ​​
> i
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ​​
> ve


​It all pretty much just allows for global mouse button usage.

There should be no behavioral change when when helm-allow-mouse is set to t
or nil​, so if you can describe one, that is a bug and I will fix it.  I
have been using global mouse keys with helm for at least a week now and
have not gotten into an unrecoverable error.  But I'm sure your usage is
more extensive and deep.

​​
> and prone to break helm in an unrecoverable way, I would accept
> ​​
>
> ​​
> but here you have to understand I can't accept such changes.
>

​Of course; no one wants that.  But like you, I need some specificity to
better understand what you are seeing and doing to do anything about it.

​​
>
> ​​
> I suggest you make an external package called helm-hyperbole that
> ​​
> provide what you want without breaking helm,


So you mean make a separate library that does what the patches do by
overriding the default helm code with code needed to allow for global mouse
bindings?  I have already separated the bindings I want for Hyperbole.

​​
> I am open to make changes
> ​​
> to helm if needed for your package as long as they don't break current
> ​​
> helm usage.
>

​Yes, that is what we both want.  I have no intent to change the default
behavior of helm, just to add to it.​

> ​​
>
> ​​
> I will close now this PR, please feel free to come back with reasonable
> ​​
> changes I will be able to merge.
>

​Please help me by summarizing the state of helm-allow-mouse, what mouse
buttons you click and in which buffers and what traceback you get.  Then if
I can replicate it, I will verify it and resolve it so it.

Once any errors are taken care of, what kinds of changes would be
acceptable to you to merge?  How would they differ from the ones offered so
far?

I really would like to make this work so others could use it to and I won't
have my own global mouse version of helm.

Thanks,

Bob

**Pull request closed without merging**
