### PR TITLE
Multiline colouration

### PR DESCRIPTION
**Pull request by Ambrevar**
Don't merge yet!

I've implemented multiline colouration by re-using the work you did.
I'll keep experimenting and foolproofing the code.

In the meantime, could you have a look at my changes?  Please question anything you find dubious.
I am discovering new grounds here, so any guidance is more than welcome :)

### CODE REVIEW

**Comment by alphapapa** [comment]
@Ambrevar Please test this with `helm-org-rifle`, as it depends on the separator and multi-line candidates.  Thanks.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Don't merge!
>
> I've implemented multiline colouration by re-using the work you did.
> I'll keep experimenting and foolproofing the code.

Thanks for working on this.
The changes I made was working quite well but had some problems in some
places, don't remember what though.

> In the meantime, could you have a look at my changes?

Yes, ASAP.

-- 
Thierry

**Comment by Ambrevar** [comment]
@alphapapa: I've tested against `helm-show-kill-ring`.  Why `helm-org-rifle` in particular?

**Comment by Ambrevar** [comment]
I've updated the changes:
- The colours have now their own faces.
- Movements are working properly it seems.

I think the existing code is overly complicated and I'm afraid my patch is not helping.  A few suggestions of what we could do:

- Remove the separator code if you agree that colour alternation is superior.
- Untangled the nested function calls.

**Comment by Ambrevar** [comment]
@thierryvolpiatto
In your original patch, you added this:
```
             do (let ((beg (point)))
                  (helm-insert-match m 'insert count source)
                  (put-text-property beg (point) 'helm-candidate
                                     (if (cl-oddp count) 'odd 'even)))
```
Why putting odd/even properties on singlelines?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've updated the changes:
>
>   * The colours have now their own faces.

Why two faces, only one face seems enough

>   * Movements are working properly it seems.
>
> I think the existing code is overly complicated and I'm afraid my
> patch is not helping. A few suggestions of what we could do:
>
>   * Remove the separator code if you agree that colour alternation is
>   superior.

No please keep the original code as it is, also I don't think using a
var to toggle face and separator for multiline is the right thing to do,
using the :multiline slot seems to be a better alternative allowing
sources with separator and others with alternate faces.
E.g. ":multiline 'face" or ":multiline 'separator", ":multiline t"
should be equivalent of ":multiline separator" for backward
compatibility.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> @thierryvolpiatto
> In your original patch, you added this:
>
>              do (let ((beg (point)))
>                   (helm-insert-match m 'insert count source)
>                   (put-text-property beg (point) 'helm-candidate
>                                      (if (cl-oddp count) 'odd 'even)))
>
> Why putting odd/even properties on singlelines?

Don't remember the details, but I guess we need the property on single
line candidates as well because they should be present among
other multiline candidates.

What we have to do on this issue is first merge the original code
(fix_multiline branch) again into master and see what's wrong with and
without multiline, when this code will be fixed let's apply your patch
on top of this.

Perhaps next week I will be more quiet to look into this more carefully.

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
> Why two faces, only one face seems enough

Well, one for odd lines, one for even lines... Did you mean something else?

I think we are misunderstood in what we want to achieve: you want sources to define how they display (separator or not) through the slot.
I don't see the point in enforcing _appearance_ to the user.  I want to be able to use `helm-show-kill-ring` with colors and not separators.

> What we have to do on this issue is first merge the original code (fix_multiline branch) again into master and see what's wrong with and without multiline, when this code will be fixed let's apply your patch on top of this.

Well, that's what I did: first commit re-applied your changes, second one fixes them (to the extend I've tested) and adds the variables/faces.

**Comment by alphapapa** [comment]
> I've tested against helm-show-kill-ring. Why helm-org-rifle in particular?

@Ambrevar Because it uses the separators and multi-line candidates in a less-common way.  I would like for it to not be broken by this patch.

**Comment by Ambrevar** [comment]
> Don't remember the details, but I guess we need the property on single
> line candidates as well because they should be present among
> other multiline candidates.

The `singleline` is not a property of candidates but of the source.  A singleline source will never need colors I believe.
As a matter of fact, the code does not deal with separators, so why should it deal with colors?

**Comment by Ambrevar** [comment]
@alphapapa: Just tested with helm-org-rifle and it seems to work without an itch.

**Comment by Ambrevar** [comment]
> > Why two faces, only one face seems enough
> Well, one for odd lines, one for even lines... Did you mean something else?

Duh, I guess you meant we can leave odd entries to the normal background color and only color even entries.  Right?  I think it's much better indeed.
I suggest dark gray and light gray for dark background and light background respectively.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>         Why two faces, only one face seems enough
>         Well, one for odd lines, one for even lines... Did you mean something else?
>
> Duh, I guess you meant we can leave odd entries to the normal
> background color and only color even entries. Right?

Yes.

> I think it's much better indeed.  I suggest dark gray and light gray
> for dark background and light background respectively.

As you want, take care however to not use something similar to
helm-selection.


--
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     Don't remember the details, but I guess we need the property on single
>     line candidates as well because they should be present among
>     other multiline candidates.
>
> The singleline is not a property of candidates but of the source. A
> singleline source will never need colors I believe.

Forget colors for now.

You may have candidates with multilines without having specified the
`:multiline` keyword, e.g.

    (helm :sources (helm-build-sync-source "test"
                     :candidates '("foo\nbar" "baz\nfoo" "bar\nfoo"))
          :buffer "*helm test*")

So here a list of 3 candidates which is displayed as a list of 6
candidates in current master branch.

The work I did previously fixed this.

> As a matter of fact, the code does not deal with separators, so why
> should it deal with colors?

I didn't have the time to investigate much, but I think we should decide
of the semantic for the :multiline keyword and where the colorisation
should happen (not sure yet if helm-render-source is the good place).

I hope I will have more time next week to look into all this more
seriously.

Thanks.
 
--
Thierry

**Comment by alphapapa** [comment]
@Ambrevar Thank you for testing it with helm-org-rifle.  :)

Forgive me if I missed this in the conversation, but please take care to not require applying the alternate colors.  For example, helm-org-rifle would not need that, and it would cause problems if it were enabled.

**Comment by Ambrevar** [comment]
It does not, in fact it works with colors too, albeit useless since helm-org-rifle is using its own separator.

As the maintainer of helm-org-rifle, why don't you want to follow upstream?  I understand you like empty separators better, but ultimately I believe that choice should be left to the user.

**Comment by Ambrevar** [comment]
I've removed the colouration of odd multilines.

**Comment by alphapapa** [comment]
> As the maintainer of helm-org-rifle, why don't you want to follow upstream? 

I'm not sure why you would think that I don't want to follow upstream.  I've worked with Thierry and contributed patches to Helm myself.

> I understand you like empty separators better, but ultimately I believe that choice should be left to the user.

When I first created helm-org-rifle, the default Helm multi-line-candidate separator was a plain string of red `----------`.  It didn't look good in helm-org-rifle results, especially because each result is a propertized Org entry with fontified heading, which provides its own visual separation, just like in an Org buffer.  So I set the separator to an empty string.

In the `helm-org-rifle-occur` commands, there is a separator, which is also a blank string, but is fontified with a customizable face.  This is important since results in that command are persistent, can be manipulated, collapsed, deleted, etc.

This sounds like a nice change for most Helm commands, but I don't think it would be good to use it in helm-org-rifle, because its results are fontified the same way they appear in Org buffers, and this would interfere with that.  So I hope that I won't have to work around this in my own code.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> This sounds like a nice change for most Helm commands, but I don't
> think it would be good to use it in helm-org-rifle, because its
> results are fontified the same way they appear in Org buffers, and
> this would interfere with that. So I hope that I won't have to work
> around this in my own code.

Nothing will change, I want the default to stay the same as before.

Also there is one new variable `helm-use-multiline-separator` that could be
removed by using only `helm-multiline-separator` with a different value,
like a symbol (face?) instead of a string.

Originally I wanted to use setting by source only using the
:multiline slot, but it looks complicated as we have to handle the
truncated width as well in this slot. 


--
Thierry

**Comment by Ambrevar** [comment]
@alphapapa:  Sorry for the misunderstanding, I did not mean to undermine your valuable contribution to Helm, far from that! :)
My question was specifically about the separator of helm-org-rifle which does not follow upstream.  But you've answered that, so all good.

> because its results are fontified the same way they appear in Org buffers, and this would interfere with that.

There is no interference: 1. The original code is still here. 2. My patch changes the _background_ colours, thus this won't interfere with any of the usual org fontification.

@thierryvolpiatto: What is `helm-multiline-separator`?

**Comment by Ambrevar** [comment]
@alphapapa: 
> It didn't look good in helm-org-rifle results, especially because each result is a propertized Org entry ? with fontified heading, which provides its own visual separation, just like in an Org buffer. So I set the separator to an empty string.

If headers are always starting entries, why not removing the separator altogether?

**Comment by alphapapa** [comment]
>  My patch changes the background colours

That might be helpful in helm-org-rifle, so I look forward to trying that.  The hard part may be getting the color right, since it depends on the user's theme.  Is there a standard Emacs color for that?  I don't think the standard `highlight` face would be a good choice, because, of course, that is how the currently selected item is shown.

> If headers are always starting entries, why not removing the separator altogether?

Because it doesn't look good with them displayed so close together.  This is especially so because headers are independent, so they may vary wildly in size, boldness, color, etc, and it looks confusing to have a small, deep heading displayed immediately before a large, shallow heading.  Also, entries have entry text, not just heading text, so without a blank line, a line of entry text might be closer to the next heading than to its own heading.

Anyway, you can experiment with the code and remove it if you don't like it.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> @thierryvolpiatto: What is helm-multiline-separator?

Sorry I meant `helm-candidate-separator`.

But I am not really sure on how to enable this for now.

I saw that your patch is working with the alternate faces but breaks
multiline with separator, selection becomes quickly erratic after moving
up and down, wrong candidate is selected when using
helm-move-to-line-cycle-in-source, only first line of some candidates is
selected etc...

-- 
Thierry

**Comment by Ambrevar** [comment]
I can reproduce two issues:

- cycle on, separator off: selection jumps back to beginning on some entries.

- cycle on, seperator on: cycling backwards from first candidate to last, the last entry is not properly selected.

**Comment by Ambrevar** [comment]
I've fixed both issues (first description was inacurate, see the commit).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've fixed both issues (first description was inacurate, see the commit).

Thanks, looks fixed indeed.

However, next/previous-line is now really slow, this is not your additions
that make helm slow but the initial patch (1/4) which need to be
reworked to make helm fast again.

To feel the difference, use master and your branch with M-x
helm-list-elisp-packages-no-fetch and try to move around with C-n/p.

-- 
Thierry

**Comment by Ambrevar** [comment]
I can't reproduce the performance issue.
I've tried with `emacs-helm.sh` and I get the same speed both on master and my branch.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I can't reproduce the performance issue.
> I've tried with emacs-helm.sh and I get the same speed both on master and my branch.

You need more than 5000 candidates and keep pressing <down> or <up> to
really see the difference.

The problem is `next-single-property-change` which is slow.

-- 
Thierry

**Comment by Ambrevar** [comment]
OK, I can reproduce with 4000 candidates.  Let's investigate.

**Comment by Ambrevar** [comment]
Here is the profile I get when I fire up `helm-list-elisp-packages-no-fetch` and keep pressing `C-n` for a few seconds:

```
- command-execute                                                4088  93%
 - call-interactively                                            4088  93%
  - funcall-interactively                                        3967  90%
   - eval-last-sexp                                              3959  90%
    - elisp--eval-last-sexp                                      3959  90%
     - eval                                                      3959  90%
      - helm-list-elisp-packages-no-fetch                        3959  90%
       - helm-list-elisp-packages                                3959  90%
        - helm                                                   3959  90%
         - apply                                                 3959  90%
          - helm                                                 3959  90%
           - apply                                               3959  90%
            - helm-internal                                      3959  90%
             - helm-read-pattern-maybe                           3629  83%
              - read-from-minibuffer                             3433  78%
               - command-execute                                 3325  76%
                - call-interactively                             3325  76%
                 - funcall-interactively                         3247  74%
                  - helm-next-line                               3247  74%
                   - helm--next-or-previous-line                 3247  74%
                    - helm-move-selection-common                 3247  74%
                     - helm-mark-current-line                    1944  44%
                      - helm-get-next-candidate-separator-pos               1276  29%
                         helm-get-next-header-pos                 660  15%
                        helm-get-next-header-pos                  660  15%
                      - helm-window                                 4   0%
                       - helm-buffer-get                            4   0%
                          helm-action-window                        4   0%
                     - helm-move--next-line-fn                   1291  29%
                      - helm-get-next-candidate-separator-pos               1291  29%
                         helm-get-next-header-pos                 655  14%
                       helm-display-mode-line                       4   0%
                     + #<compiled 0x1d2bfab>                        4   0%
                 + byte-code                                       78   1%
               + redisplay_internal (C function)                   68   1%
              + helm-update                                       184   4%
                helm-get-candidate-number                           4   0%
             + helm-initialize                                    326   7%
             + #<compiled 0xc5c105>                                 4   0%
   + helm-M-x                                                       8   0%
  + byte-code                                                     121   2%
+ ...                                                             275   6%
+ redisplay_internal (C function)                                   4   0%
```

**Comment by Ambrevar** [comment]
Same profiling procedure on master:
```
- command-execute                                                2916  91%
 - call-interactively                                            2916  91%
  - funcall-interactively                                        2761  86%
   - eval-last-sexp                                              2761  86%
    - elisp--eval-last-sexp                                      2761  86%
     - eval                                                      2761  86%
      - helm-list-elisp-packages-no-fetch                        2761  86%
       - helm-list-elisp-packages                                2761  86%
        - helm                                                   2761  86%
         - apply                                                 2761  86%
          - helm                                                 2761  86%
           - apply                                               2761  86%
            - helm-internal                                      2761  86%
             - helm-read-pattern-maybe                           2442  76%
              - read-from-minibuffer                             2272  70%
               + redisplay_internal (C function)                 1172  36%
               - command-execute                                    4   0%
                - call-interactively                                4   0%
                 - funcall-interactively                            4   0%
                  - helm-next-line                                  3   0%
                   - helm--next-or-previous-line                    3   0%
                    - helm-move-selection-common                    3   0%
                       helm-follow-execute-persistent-action-maybe                  3   0%
               + timer-event-handler                                2   0%
              + helm-update                                       142   4%
                helm-get-candidate-number                           8   0%
             + helm-initialize                                    313   9%
             + #<compiled 0x9efaf7>                                 6   0%
  + byte-code                                                     155   4%
+ ...                                                             288   8%
```

**Comment by Ambrevar** [comment]
I've fixed the issue.]I've rebased my changes over your master branch since there were some conflicts.  The fix commit is on my master branch, but somehow GitHub does not see the new commit on this PR.  Am I missing something or should I open a new PR?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've fixed the issue.]I've rebased my changes over your master branch
> since there were some conflicts. The fix commit is on my master
> branch, but somehow GitHub does not see the new commit on this PR.

I can see it from here, I will try and look at your new patch ASAP.
Thanks.

> Am I missing something or should I open a new PR?

Perhaps reload the github page ?

--
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thievol05@zoho.eu> writes:

> Pierre Neidhardt <notifications@github.com> writes:
>
>> I've fixed the issue.

It is not fixed here it still unusable on large set of candidates.
The problem is coming from `helm--forward-candidate` and
`helm--backward-candidate` that are calling
`next-single-char-property-change` and `previous-single-property-change`
which are really slow.

Sorry to not help more, but I have not much time to read/write code
actually apart for trivial changes, perhaps next week I will have some
time to work on this.

-- 
Thierry

**Comment by Ambrevar** [comment]
> Perhaps reload the github page ?

It took ages to refresh.

> It is not fixed here it still unusable on large set of candidates.

I'll see if I can reproduce.

**Comment by Ambrevar** [comment]
I cannot reproduce: it's really fast with my patch.  Here is the profile:

```
- command-execute                                                3950  92%
 - call-interactively                                            3950  92%
  - funcall-interactively                                        3806  89%
   - eval-last-sexp                                              3802  89%
    - elisp--eval-last-sexp                                      3802  89%
     - eval                                                      3802  89%
      - helm-test-init                                           3802  89%
       - helm-list-elisp-packages-no-fetch                       3653  85%
        - helm-list-elisp-packages                               3653  85%
         - helm                                                  3653  85%
          - apply                                                3653  85%
           - helm                                                3653  85%
            - apply                                              3653  85%
             - helm-internal                                     3653  85%
              - helm-read-pattern-maybe                          3337  78%
               - read-from-minibuffer                            3146  74%
                - command-execute                                1590  37%
                 - call-interactively                            1590  37%
                  - funcall-interactively                        1590  37%
                   - helm-next-line                              1590  37%
                    - helm--next-or-previous-line                1590  37%
                     - helm-move-selection-common                1590  37%
                      - helm-move--next-line-fn                  1578  37%
                       - helm-get-next-candidate-separator-pos               1574  37%
                          helm-get-next-header-pos                810  19%
                        helm-display-mode-line                     12   0%
                + redisplay_internal (C function)                 973  22%
               + helm-update                                      156   3%
                 helm-get-candidate-number                         12   0%
              + helm-initialize                                   310   7%
              + #<compiled 0x90a613>                                6   0%
       + package-refresh-contents                                 147   3%
       + package-initialize                                         2   0%
   + helm-M-x                                                       4   0%
  + byte-code                                                     144   3%
+ ...                                                             300   7%

```

**Comment by Ambrevar** [comment]
On master, `redisplay_internal` is the bottleneck at 36% while `command-execute` takes 0%.
With my patch, `redisplay_internal` takes 22% while `command-execute` takes 37%.

The slow part is seemingly around the new `helm-get-next-candidate-separator-pos`. I'll see how we can optimize this.

**Comment by Ambrevar** [comment]
So the offending part is this:
```
(defun helm-move--next-line-fn ()
  (cond ((and (not (helm-pos-multiline-p))
              (helm-get-next-candidate-separator-pos))
        ((not (helm-pos-multiline-p))
         (helm--forward-candidate))
        (t (helm-move--next-multi-line-fn)))
```

And more specifically:
```
  (cond ((and (not (helm-pos-multiline-p))
              (helm-get-next-candidate-separator-pos))
```

While I understand the last 2 conditions, why the first one?
If this is not multiline, then there should be no separator, or am I mistaken?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> While I understand the last 2 conditions, why the first one?
> If this is not multiline, then there should be no separator, or am I mistaken?

helm-pos-multiline-p tells you if you are on a separator line, not you
are using multiline or not.

-- 
Thierry

**Comment by Ambrevar** [comment]
That's a confusing name then :p

Can you detail the meaning of the algorithm?  Here is what I understand:

Cond:

- If not on a separator line (no cost) and there is a separator somewhere down below (scans the whole buffer, super costly `O(n)`), forward line.  Why would we do that?  Why the check and why forwarding line?

- If not on a separator, go to next candidate.  Makes sense.

- If on a separator, move to next multiline.  Mes sense.

Assuming first condition is really needed, a possible fix would be to check if it's a multiline source and we are last candidate.  But I still don't get the point.

**Comment by Ambrevar** [comment]
Any insight?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Any insight?

I have no idea on how to implement it for now (faster than what we
have).

-- 
Thierry

**Comment by Ambrevar** [comment]
Can you explain the intention of the first condition mentioned above?

Also here is an optimization idea, no clue if that'd be faster though. When looking for the next separator,
```
(defun helm-get-next-candidate-separator-pos ()
  "Return the position of the next candidate separator from point."
  (let ((hp (helm-get-next-header-pos)))
    (helm-aif (next-single-property-change (point) 'helm-candidate-separator)
```

Instead of scanning all characters, why not scanning the first character of every line?
(Assuming separators can only be on their own line.)

That would probably involve Lisp code instead of C, so that could actually be slower.

**Comment by Ambrevar** [comment]
Are you dropping this?
Sorry for the long radio-silence, but I was eventually thinking of giving it another shot at some point.  What do you think?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Are you dropping this?

Yes, this implementation is not the good approach anyway.

> Sorry for the long radio-silence, but I was eventually thinking of
> giving it another shot at some point. What do you think?

As you want, make another PR if needed, keep in mind what we need is
performance, previous implementation was too slow to be usable.

--
Thierry

**Pull request closed without merging**
